/mnt/hwfile/huqinghao/miniconda3/bin/python
2024-05-17 16:20:54,703 - INFO - Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2024-05-17 16:20:54,703 - INFO - Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-05-17 16:20:54,703 - INFO - NumExpr defaulting to 8 threads.
2024-05-17 16:20:56,331	INFO scripts.py:1182 -- Did not find any active Ray processes.

==========
== CUDA ==
==========

CUDA Version 12.1.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1450>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 05-17 16:21:10 api_server.py:191] vLLM API server version 0.3.3
INFO 05-17 16:21:10 api_server.py:192] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, lora_modules=[], delta_modules=[Delta(name='delta-1', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1'), Delta(name='delta-2', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2'), Delta(name='delta-3', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3'), Delta(name='delta-4', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4'), Delta(name='delta-5', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5'), Delta(name='delta-6', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6'), Delta(name='delta-7', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7'), Delta(name='delta-8', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8'), Delta(name='delta-9', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-9'), Delta(name='delta-10', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-10'), Delta(name='delta-11', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-11'), Delta(name='delta-12', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-12'), Delta(name='delta-13', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-13'), Delta(name='delta-14', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-14'), Delta(name='delta-15', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-15'), Delta(name='delta-16', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-16'), Delta(name='delta-17', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-17'), Delta(name='delta-18', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-18'), Delta(name='delta-19', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-19'), Delta(name='delta-20', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-20'), Delta(name='delta-21', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-21'), Delta(name='delta-22', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-22'), Delta(name='delta-23', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-23'), Delta(name='delta-24', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-24'), Delta(name='delta-25', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-25'), Delta(name='delta-26', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-26'), Delta(name='delta-27', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-27'), Delta(name='delta-28', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-28'), Delta(name='delta-29', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-29'), Delta(name='delta-30', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-30'), Delta(name='delta-31', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-31'), Delta(name='delta-32', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-32')], swap_modules=[], chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, seed=0, swap_space=4, gpu_memory_utilization=0.85, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=True, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=64, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=32, enable_delta=True, max_deltas=24, max_cpu_deltas=32, max_delta_bitwidth=4, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_prefetch=False, scheduler_policy='fcfs', max_swap_slots=1, max_cpu_models=4, enable_swap=False, engine_use_ray=False, disable_log_requests=True, max_log_len=None)
2024-05-17 16:21:14,257	INFO worker.py:1749 -- Started a local Ray instance.
INFO 05-17 16:21:16 llm_engine.py:90] Initializing an LLM engine (v0.3.3) with config: model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, lora_config=None, delta_config=DeltaConfig(max_deltas=24, max_bitwidth=4, delta_dtype=torch.int8, max_cpu_deltas=32, delta_extra_vocab_size=0, pack_factor=Fraction(2, 1), kernel=<QuantKernel.TRITON: 'triton'>), swap_config=None, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, seed=0)
INFO 05-17 16:21:16 llm_engine.py:243] ignored verifying delta_config
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f12d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f02b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception ignored in: <function TempDirectory.__del__ at 0x7f21882d7eb0>
Traceback (most recent call last):
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
    self.remove()
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
    if self.temp_dir:
AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1d20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception ignored in: <function TempDirectory.__del__ at 0x7f21882d7eb0>
Traceback (most recent call last):
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
    self.remove()
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
    if self.temp_dir:
AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Exception ignored in: <function TempDirectory.__del__ at 0x7f21882d7eb0>
Traceback (most recent call last):
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
    self.remove()
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
    if self.temp_dir:
AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f25f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2c80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f23b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f04f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1480>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2200>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1db0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1300>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f14e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f19f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f22c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f37f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f26e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2140>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f34c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1840>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2e00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2a70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f21a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee40a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2620>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f12d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f34c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2da0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2980>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f20b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f06a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f20e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f36a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee4520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Using bitblas
BitBLAS Operator not loaded, retrying in 5 seconds...
Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
BitBLAS Operator not loaded, retrying in 5 seconds...
Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
BitBLAS Operator not loaded, retrying in 5 seconds...
Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
WARNING 05-17 16:31:14 models.py:48] Using bitblas delta modules
INFO 05-17 16:31:14 selector.py:16] Using FlashAttention backend.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1720>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=112846)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7ef1a4152200>
[36m(RayWorkerVllm pid=112846)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=112846)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=112846)[0m     self.remove()
[36m(RayWorkerVllm pid=112846)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=112846)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=112846)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=113171)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7ef1a395e200>
[36m(RayWorkerVllm pid=113171)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=113171)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=113171)[0m     self.remove()
[36m(RayWorkerVllm pid=113171)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=113171)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=113171)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=113171)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7ef1a395e200>
[36m(RayWorkerVllm pid=113171)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=113171)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=113171)[0m     self.remove()
[36m(RayWorkerVllm pid=113171)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=113171)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=113171)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f27a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee49a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2410>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f30a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee4340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1720>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f12d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f28c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f31f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee4790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee4be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1750>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2c80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f27d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f06d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee52a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1a50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2320>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f30d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f35e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee4820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1750>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1a80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2440>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2950>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1210>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1750>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f14b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f24a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee56f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f11e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f16c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=113171)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7ef1a395e200>
[36m(RayWorkerVllm pid=113171)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=113171)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=113171)[0m     self.remove()
[36m(RayWorkerVllm pid=113171)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=113171)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=113171)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f09a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f04c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1480>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee4d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f27a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f18a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee5600>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1330>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1720>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f10c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1db0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee43d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee5240>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1510>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2fb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee5ba0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f35b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee4040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0160>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee4ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1480>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b04ee5de0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2e60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f0670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f3a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=112846)[0m Using bitblas
[36m(RayWorkerVllm pid=112994)[0m Using bitblas
[36m(RayWorkerVllm pid=113171)[0m Using bitblas
[36m(RayWorkerVllm pid=112846)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=112846)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=113171)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=113171)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=113171)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=113171)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=113171)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=113171)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/0c90e7f5ea1268ab82987e20fadda49d178b7e79556d9e1758831293d3c4f853/tvm_rt_mod'
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:40:02 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:40:02 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:40:04 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:40:04 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:48:46 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:48:46 selector.py:16] Using FlashAttention backend.
INFO 05-17 16:48:58 model_runner.py:161] Loading model weights took 6.1114 GB
INFO 05-17 16:48:58 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:49:00 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:49:00 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:49:00 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:49:00 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:49:00 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:49:00 worker_manager.py:297] Starting prefetching thread
WARNING 05-17 16:49:02 quant_linear_triton.py:557] We should warm up the kernel here 
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f2d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:49:03 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:49:03 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:49:03 quant_linear_triton.py:557] We should warm up the kernel here 
INFO 05-17 16:49:16 ray_gpu_executor.py:275] # GPU blocks: 6431, # CPU blocks: 1310
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b052f1480>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 05-17 16:49:18 scheduler.py:136] Using fcfs policy.
INFO 05-17 16:49:18 block_manager.py:264] disable automatic prefix caching
WARNING 05-17 16:49:19 serving_chat.py:373] No chat template provided. Chat API will not work.
INFO:     Started server process [104487]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     ::1:49312 - "GET /sysinfo HTTP/1.1" 200 OK
Translating from base-model to /vllm/.idea/full_models/Llama-2-13b-hf
Warming up starts
{'id': 76, 'prompt': 'USER: Please write C++ code to read network packets from a socket on port 888\nASSISTANT:', 'timestamp': 0, 'model': 'delta-10', 'min_tokens': 380, 'max_tokens': 380}
Prefetching is disabled
WARNING 05-17 16:49:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
INFO 05-17 16:49:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:49:28 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:49:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:49:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:49:28 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:49:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:49:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:49:28 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:49:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:49:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:49:28 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:49:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:49:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:49:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.181 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:49:42 worker_manager.py:364] Main thread loading delta 10 done
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:49:42 worker_manager.py:379] [1715935782.739382] activating delta
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:49:42 worker_manager.py:384] [1715935782.8691678] CPU -> GPU time: 0.1297
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:49:43 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.137 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:49:43 worker_manager.py:364] Main thread loading delta 10 done
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:49:43 worker_manager.py:379] [1715935783.6983073] activating delta
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:49:43 worker_manager.py:384] [1715935783.8249545] CPU -> GPU time: 0.1266
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:49:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.135 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:49:44 worker_manager.py:364] Main thread loading delta 10 done
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:49:44 worker_manager.py:379] [1715935784.7074666] activating delta
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:49:44 worker_manager.py:384] [1715935784.8391924] CPU -> GPU time: 0.1317
INFO 05-17 16:49:47 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 19.486 seconds
INFO 05-17 16:49:48 worker_manager.py:364] Main thread loading delta 10 done
INFO 05-17 16:49:48 worker_manager.py:379] [1715935788.0479429] activating delta
INFO 05-17 16:49:48 worker_manager.py:384] [1715935788.1511438] CPU -> GPU time: 0.1031
INFO 05-17 16:49:48 metrics.py:276] Avg prompt throughput: 2.9 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:49:53 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:49:58 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:08 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:13 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:00 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:05 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:15 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:20 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO:     ::1:49314 - "POST /v1/completions HTTP/1.1" 200 OK
Warming up ends
Issuing queries
sending 1 queries at 0.2
sending 1 queries at 0.4
sending 1 queries at 0.5
sending 1 queries at 0.7000000000000001
sending 1 queries at 0.8
sending 1 queries at 0.9
sending 1 queries at 1.0
sending 1 queries at 1.4000000000000001
sending 2 queries at 2.0
sending 1 queries at 2.3000000000000003
sending 1 queries at 2.4000000000000004
sending 1 queries at 2.6
sending 4 queries at 3.0
sending 1 queries at 3.3000000000000003
sending 1 queries at 3.6
sending 1 queries at 3.9000000000000004
sending 1 queries at 4.6000000000000005
sending 1 queries at 4.800000000000001
sending 1 queries at 4.9
sending 2 queries at 5.2
sending 2 queries at 5.4
sending 1 queries at 5.9
sending 1 queries at 6.0
sending 2 queries at 6.1000000000000005
sending 1 queries at 6.4
sending 1 queries at 6.5
sending 2 queries at 6.6000000000000005
sending 1 queries at 6.800000000000001
sending 1 queries at 7.0
sending 1 queries at 7.1000000000000005
sending 1 queries at 7.6000000000000005
sending 1 queries at 7.800000000000001
sending 1 queries at 7.9
sending 1 queries at 8.0
sending 2 queries at 8.200000000000001
sending 1 queries at 8.4
sending 1 queries at 8.5
sending 2 queries at 8.6
sending 2 queries at 8.700000000000001
sending 1 queries at 8.9
sending 1 queries at 9.0
sending 2 queries at 9.700000000000001
sending 2 queries at 9.8
sending 2 queries at 10.0
sending 1 queries at 10.100000000000001
sending 3 queries at 10.200000000000001
sending 2 queries at 10.4
sending 2 queries at 10.5
sending 2 queries at 10.8
sending 2 queries at 11.200000000000001
sending 1 queries at 11.8
sending 1 queries at 11.9
sending 1 queries at 12.5
sending 1 queries at 12.700000000000001
sending 2 queries at 12.9
sending 3 queries at 13.0
sending 2 queries at 13.100000000000001
sending 2 queries at 13.200000000000001
sending 1 queries at 13.4
sending 2 queries at 13.600000000000001
sending 1 queries at 13.700000000000001
sending 1 queries at 13.8
sending 1 queries at 13.9
sending 1 queries at 14.3
sending 1 queries at 14.4
sending 2 queries at 14.600000000000001
sending 1 queries at 14.8
sending 2 queries at 14.9
sending 2 queries at 15.100000000000001
sending 2 queries at 15.4
sending 1 queries at 15.5
sending 1 queries at 15.600000000000001
sending 1 queries at 15.8
sending 2 queries at 16.400000000000002
sending 1 queries at 16.6
sending 1 queries at 16.7
sending 2 queries at 16.900000000000002
sending 1 queries at 17.400000000000002
sending 1 queries at 17.5
sending 1 queries at 17.8
sending 1 queries at 18.0
sending 1 queries at 18.1
sending 2 queries at 18.400000000000002
sending 1 queries at 18.8
sending 1 queries at 18.900000000000002
sending 1 queries at 19.3
sending 1 queries at 19.5
sending 1 queries at 19.700000000000003
sending 1 queries at 19.8
sending 1 queries at 20.3
sending 1 queries at 20.5
sending 1 queries at 20.6
sending 3 queries at 20.8
sending 1 queries at 21.0
sending 1 queries at 21.1
sending 1 queries at 21.200000000000003
sending 2 queries at 21.3
sending 1 queries at 21.400000000000002
sending 1 queries at 21.5
sending 1 queries at 21.700000000000003
sending 1 queries at 21.8
sending 1 queries at 22.0
sending 1 queries at 22.200000000000003
sending 1 queries at 22.3
sending 2 queries at 22.700000000000003
sending 1 queries at 22.8
sending 1 queries at 23.200000000000003
sending 1 queries at 23.5
sending 2 queries at 23.700000000000003
sending 1 queries at 24.1
sending 1 queries at 24.3
sending 1 queries at 25.400000000000002
sending 1 queries at 25.5
sending 2 queries at 25.8
sending 2 queries at 26.0
sending 1 queries at 26.3
sending 1 queries at 26.6
sending 2 queries at 26.8
sending 1 queries at 26.900000000000002
sending 1 queries at 27.0
sending 1 queries at 27.200000000000003
sending 1 queries at 27.400000000000002
sending 1 queries at 27.700000000000003
sending 1 queries at 28.3
sending 2 queries at 28.6
sending 1 queries at 28.700000000000003
sending 1 queries at 28.900000000000002
sending 1 queries at 29.0
sending 4 queries at 29.1
sending 2 queries at 29.400000000000002
sending 1 queries at 29.5
sending 1 queries at 30.0
Prefetching is disabled
WARNING 05-17 16:51:23 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
INFO 05-17 16:51:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:51:23 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:51:23 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:23 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:51:23 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:23 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:51:23 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:23 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:51:25 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.549 seconds
INFO 05-17 16:51:25 worker_manager.py:364] Main thread loading delta 1 done
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:25 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.001 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:25 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.041 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:25 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.080 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:25 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:25 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:26 worker_manager.py:364] Main thread loading delta 1 done
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:51:26 metrics.py:276] Avg prompt throughput: 3.5 tokens/s, Avg generation throughput: 2.2 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
WARNING 05-17 16:51:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
INFO 05-17 16:51:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:51:26 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:51:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:26 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:51:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:26 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:51:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:26 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:51:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.512 seconds
INFO 05-17 16:51:28 worker_manager.py:364] Main thread loading delta 4 done
Prefetching is disabled
WARNING 05-17 16:51:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
INFO 05-17 16:51:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:51:28 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.999 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.036 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.071 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:28 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:28 worker_manager.py:364] Main thread loading delta 4 done
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:51:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:28 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:28 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:51:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:28 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:51:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:28 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:51:29 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.504 seconds
INFO 05-17 16:51:29 worker_manager.py:364] Main thread loading delta 6 done
Prefetching is disabled
WARNING 05-17 16:51:30 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
INFO 05-17 16:51:30 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:51:30 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:30 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.961 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:30 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:30 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.961 seconds
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:51:31 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:31 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:30 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:30 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.024 seconds
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:51:31 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:31 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:31 worker_manager.py:364] Main thread loading delta 6 done
Prefetching is disabled
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:51:31 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:31 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:51:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:45 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.797 seconds
Prefetching is disabled
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:45 worker_manager.py:364] Main thread loading delta 9 done
Prefetching is disabled
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:51:45 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:45 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:51:45 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.961 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:46 worker_manager.py:364] Main thread loading delta 9 done
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:51:46 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:46 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:46 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:48 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.693 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:48 worker_manager.py:364] Main thread loading delta 9 done
INFO 05-17 16:51:48 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.874 seconds
INFO 05-17 16:51:49 worker_manager.py:364] Main thread loading delta 9 done
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:51:48 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:48 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:51:48 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
WARNING 05-17 16:51:49 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
INFO 05-17 16:51:49 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:51:49 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:51:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
total threads: 178
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.628 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:57 worker_manager.py:364] Main thread loading delta 13 done
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:51:58 worker_manager.py:344] Missed prefetch, fall back to loading delta 21 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:58 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:51:58 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:51:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:52:06 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.586 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:06 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 21.430 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:06 worker_manager.py:364] Main thread loading delta 13 done
INFO 05-17 16:52:06 worker_manager.py:364] Main thread loading delta 13 done
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:52:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 21 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:06 models.py:263] [main] Lossless Compression Disabled
WARNING 05-17 16:52:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 21 now
INFO 05-17 16:52:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:52:06 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:07 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.450 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:07 worker_manager.py:364] Main thread loading delta 13 done
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:52:07 worker_manager.py:344] Missed prefetch, fall back to loading delta 21 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:07 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:07 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:52:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:11 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.504 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:11 worker_manager.py:364] Main thread loading delta 21 done
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:52:11 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:12 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:12 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:19 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.351 seconds
INFO 05-17 16:52:19 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:19 worker_manager.py:364] Main thread loading delta 21 done
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:52:19 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:19 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:19 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:20 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.254 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:20 worker_manager.py:364] Main thread loading delta 21 done
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:52:21 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:21 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:21 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:52:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.105 seconds
INFO 05-17 16:52:23 worker_manager.py:364] Main thread loading delta 21 done
WARNING 05-17 16:52:23 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
INFO 05-17 16:52:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:52:23 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.611 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:23 worker_manager.py:364] Main thread loading delta 22 done
INFO 05-17 16:52:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:30 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.186 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:30 worker_manager.py:364] Main thread loading delta 22 done
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:31 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.135 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:31 worker_manager.py:364] Main thread loading delta 22 done
INFO 05-17 16:52:35 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.863 seconds
INFO 05-17 16:52:35 worker_manager.py:364] Main thread loading delta 22 done
INFO 05-17 16:52:37 metrics.py:276] Avg prompt throughput: 37.7 tokens/s, Avg generation throughput: 1.5 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
WARNING 05-17 16:52:37 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
INFO 05-17 16:52:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:52:37 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:52:37 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:37 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:52:37 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:37 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:52:37 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:37 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:52:39 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.499 seconds
INFO 05-17 16:52:39 worker_manager.py:364] Main thread loading delta 2 done
WARNING 05-17 16:52:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
INFO 05-17 16:52:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:52:39 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 3.009 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 3.013 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 3.058 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:40 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:40 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:40 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:52:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:40 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:52:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:40 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:52:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:40 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:52:41 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.496 seconds
INFO 05-17 16:52:41 worker_manager.py:364] Main thread loading delta 3 done
WARNING 05-17 16:52:41 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
INFO 05-17 16:52:41 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:52:41 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.019 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.064 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:42 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.075 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:42 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:52:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:42 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:42 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:52:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:42 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:52:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:42 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:52:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.591 seconds
INFO 05-17 16:52:44 worker_manager.py:364] Main thread loading delta 5 done
WARNING 05-17 16:52:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
INFO 05-17 16:52:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:52:44 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 3.540 seconds
INFO 05-17 16:52:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.826 seconds
INFO 05-17 16:52:46 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:46 worker_manager.py:364] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 3.452 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 3.531 seconds
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:52:46 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:46 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:46 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:46 worker_manager.py:364] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:46 worker_manager.py:364] Main thread loading delta 5 done
WARNING 05-17 16:52:46 worker_manager.py:344] Missed prefetch, fall back to loading delta 8 now
INFO 05-17 16:52:46 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:52:46 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:52:46 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:46 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:46 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:52:46 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:46 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:46 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:52:49 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.458 seconds
INFO 05-17 16:52:49 worker_manager.py:364] Main thread loading delta 8 done
INFO 05-17 16:52:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 123 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
WARNING 05-17 16:52:49 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
INFO 05-17 16:52:49 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:52:49 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:49 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.988 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:49 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:49 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 3.036 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:49 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 3.021 seconds
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:52:49 worker_manager.py:344] Missed prefetch, fall back to loading delta 8 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:49 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:49 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:49 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:49 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:52:50 worker_manager.py:344] Missed prefetch, fall back to loading delta 8 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:50 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:50 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:52:50 worker_manager.py:344] Missed prefetch, fall back to loading delta 8 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:50 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:50 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:51 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.085 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:51 worker_manager.py:364] Main thread loading delta 8 done
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:52:52 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:52 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:52:52 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:52 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.126 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:52 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.080 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:52 worker_manager.py:364] Main thread loading delta 8 done
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:52 worker_manager.py:364] Main thread loading delta 8 done
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:52:52 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:52 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:52:52 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:52:52 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:52 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:52:52 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:52:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 123 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:53:03 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.680 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:03 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.913 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:03 worker_manager.py:364] Main thread loading delta 11 done
INFO 05-17 16:53:03 worker_manager.py:364] Main thread loading delta 11 done
WARNING 05-17 16:53:03 worker_manager.py:344] Missed prefetch, fall back to loading delta 12 now
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:53:03 worker_manager.py:344] Missed prefetch, fall back to loading delta 12 now
INFO 05-17 16:53:03 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:53:03 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:03 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:03 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:05 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.778 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:05 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:53:05 worker_manager.py:344] Missed prefetch, fall back to loading delta 12 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:05 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:05 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:53:09 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.800 seconds
INFO 05-17 16:53:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 123 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:53:09 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:53:09 worker_manager.py:344] Missed prefetch, fall back to loading delta 12 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:53:09 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:53:09 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:15 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.398 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:15 worker_manager.py:364] Main thread loading delta 12 done
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:53:15 worker_manager.py:344] Missed prefetch, fall back to loading delta 15 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:15 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:15 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:16 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.160 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:16 worker_manager.py:364] Main thread loading delta 12 done
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:53:16 worker_manager.py:344] Missed prefetch, fall back to loading delta 15 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:16 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:16 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:53:19 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 123 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:53:19 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.319 seconds
INFO 05-17 16:53:19 worker_manager.py:364] Main thread loading delta 12 done
WARNING 05-17 16:53:20 worker_manager.py:344] Missed prefetch, fall back to loading delta 15 now
INFO 05-17 16:53:20 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:53:20 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:53:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 123 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:31 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.179 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:31 worker_manager.py:364] Main thread loading delta 15 done
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:53:31 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:31 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:32 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.339 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:32 worker_manager.py:364] Main thread loading delta 15 done
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:53:32 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:32 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:32 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:53:35 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 25.606 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:53:35 worker_manager.py:364] Main thread loading delta 12 done
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:53:35 worker_manager.py:344] Missed prefetch, fall back to loading delta 15 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:53:35 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:53:35 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:53:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 123 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.104 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:42 worker_manager.py:364] Main thread loading delta 18 done
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:53:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:53:42 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:53:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 22.964 seconds
INFO 05-17 16:53:43 worker_manager.py:364] Main thread loading delta 15 done
WARNING 05-17 16:53:43 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
INFO 05-17 16:53:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:53:43 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.864 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:44 worker_manager.py:364] Main thread loading delta 18 done
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:53:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:44 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:53:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 123 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:53:49 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.103 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:53:49 worker_manager.py:364] Main thread loading delta 15 done
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:53:49 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:53:49 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:53:49 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:58 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.222 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:58 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:53:58 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:59 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:53:59 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:53:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 123 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:01 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.454 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:01 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:54:01 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:01 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:01 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:54:02 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 19.036 seconds
INFO 05-17 16:54:02 worker_manager.py:364] Main thread loading delta 18 done
WARNING 05-17 16:54:02 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
INFO 05-17 16:54:02 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:54:02 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:02 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.999 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:02 worker_manager.py:364] Main thread loading delta 18 done
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:54:02 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:02 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:02 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:54:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 123 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:54:09 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.424 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:54:09 worker_manager.py:364] Main thread loading delta 23 done
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:54:09 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:54:09 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:54:09 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:15 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.734 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:15 worker_manager.py:364] Main thread loading delta 23 done
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:54:15 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:15 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:15 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:17 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.062 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:17 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:54:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:18 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:54:19 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 123 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:54:20 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.653 seconds
INFO 05-17 16:54:20 worker_manager.py:364] Main thread loading delta 20 done
WARNING 05-17 16:54:20 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
INFO 05-17 16:54:20 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:54:20 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.686 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:28 worker_manager.py:364] Main thread loading delta 26 done
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:54:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 27 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:28 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:54:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 123 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:29 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.205 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:29 worker_manager.py:364] Main thread loading delta 23 done
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:54:29 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:29 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:29 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:54:34 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.770 seconds
INFO 05-17 16:54:34 worker_manager.py:364] Main thread loading delta 23 done
WARNING 05-17 16:54:34 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
INFO 05-17 16:54:34 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:54:34 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:35 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.094 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:35 worker_manager.py:364] Main thread loading delta 27 done
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:54:35 worker_manager.py:344] Missed prefetch, fall back to loading delta 28 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:35 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:35 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:54:37 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 27.581 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:54:37 worker_manager.py:364] Main thread loading delta 26 done
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:54:37 worker_manager.py:344] Missed prefetch, fall back to loading delta 27 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:54:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:54:37 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:54:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 123 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:39 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 9.913 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:39 worker_manager.py:364] Main thread loading delta 26 done
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:54:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 27 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:39 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:54:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 123 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:54:50 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.261 seconds
INFO 05-17 16:54:50 worker_manager.py:364] Main thread loading delta 26 done
WARNING 05-17 16:54:50 worker_manager.py:344] Missed prefetch, fall back to loading delta 27 now
INFO 05-17 16:54:50 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:54:50 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:54:50 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.210 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:54:50 worker_manager.py:364] Main thread loading delta 27 done
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:50 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.306 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:54:50 worker_manager.py:364] Main thread loading delta 28 done
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:54:50 worker_manager.py:344] Missed prefetch, fall back to loading delta 28 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:54:50 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:54:50 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:53 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.503 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:53 worker_manager.py:364] Main thread loading delta 27 done
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:54:53 worker_manager.py:344] Missed prefetch, fall back to loading delta 28 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:53 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:54:53 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:54:59 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 8.305 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:54:59 worker_manager.py:364] Main thread loading delta 28 done
INFO 05-17 16:54:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 123 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:55:01 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.610 seconds
INFO 05-17 16:55:01 worker_manager.py:364] Main thread loading delta 27 done
WARNING 05-17 16:55:01 worker_manager.py:344] Missed prefetch, fall back to loading delta 28 now
INFO 05-17 16:55:01 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:55:01 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:55:01 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 8.202 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:55:01 worker_manager.py:364] Main thread loading delta 28 done
INFO 05-17 16:55:08 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.404 seconds
INFO 05-17 16:55:08 worker_manager.py:364] Main thread loading delta 28 done
INFO 05-17 16:55:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 123 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:55:19 metrics.py:276] Avg prompt throughput: 411.0 tokens/s, Avg generation throughput: 11.2 tokens/s, Running: 122 reqs, Swapped: 0 reqs, Pending: 55 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
INFO:     ::1:49650 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-17 16:55:19 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
INFO 05-17 16:55:19 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:55:19 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 16:55:19 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:55:19 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:55:19 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 16:55:19 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:55:19 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:55:19 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 16:55:19 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:55:19 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:55:19 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:55:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 176 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 8.4%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:55:33 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.626 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 16:55:33 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:55:36 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.009 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 16:55:36 worker_manager.py:364] Main thread loading delta 14 done
INFO 05-17 16:55:37 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.545 seconds
INFO 05-17 16:55:37 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:55:38 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.951 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 16:55:38 worker_manager.py:364] Main thread loading delta 14 done
INFO 05-17 16:55:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 176 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 8.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:55:46 metrics.py:276] Avg prompt throughput: 392.8 tokens/s, Avg generation throughput: 7.6 tokens/s, Running: 176 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 8.4%, CPU KV cache usage: 0.0%
INFO:     ::1:49962 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49680 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:55:53 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 49.7 tokens/s, Running: 174 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 8.7%, CPU KV cache usage: 0.0%
INFO:     ::1:49986 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:55:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 29.7 tokens/s, Running: 173 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 8.9%, CPU KV cache usage: 0.0%
INFO:     ::1:49674 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49638 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49806 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49692 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:50004 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49686 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49688 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:56:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 61.9 tokens/s, Running: 164 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 8.8%, CPU KV cache usage: 0.0%
INFO:     ::1:49982 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49684 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:56:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 46.7 tokens/s, Running: 159 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 8.7%, CPU KV cache usage: 0.0%
INFO:     ::1:50024 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49980 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49780 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49786 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49700 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49936 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:56:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 45.2 tokens/s, Running: 155 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 8.9%, CPU KV cache usage: 0.0%
INFO:     ::1:50044 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49690 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49840 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49634 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:56:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 44.4 tokens/s, Running: 153 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 9.2%, CPU KV cache usage: 0.0%
INFO:     ::1:49868 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49972 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49938 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:56:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 43.6 tokens/s, Running: 151 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 9.5%, CPU KV cache usage: 0.0%
INFO 05-17 16:56:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 43.6 tokens/s, Running: 151 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 10.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:56:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.0 tokens/s, Running: 151 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 10.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:56:56 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 64.5 tokens/s, Running: 151 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 10.5%, CPU KV cache usage: 0.0%
INFO:     ::1:49958 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:57:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 43.3 tokens/s, Running: 148 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 10.5%, CPU KV cache usage: 0.0%
INFO:     ::1:49814 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49872 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49714 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:57:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 24.6 tokens/s, Running: 147 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 10.6%, CPU KV cache usage: 0.0%
INFO:     ::1:49910 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:57:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 56.1 tokens/s, Running: 146 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 10.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:57:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 42.3 tokens/s, Running: 145 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 11.1%, CPU KV cache usage: 0.0%
INFO:     ::1:49702 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:57:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.5 tokens/s, Running: 145 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 11.5%, CPU KV cache usage: 0.0%
INFO:     ::1:49778 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:50000 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:57:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 56.8 tokens/s, Running: 142 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 11.6%, CPU KV cache usage: 0.0%
INFO:     ::1:49668 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:57:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 41.2 tokens/s, Running: 142 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 12.0%, CPU KV cache usage: 0.0%
INFO:     ::1:49646 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49802 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:57:48 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 40.9 tokens/s, Running: 139 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 12.0%, CPU KV cache usage: 0.0%
INFO:     ::1:49874 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:57:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 40.3 tokens/s, Running: 138 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 12.1%, CPU KV cache usage: 0.0%
INFO:     ::1:49970 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:58:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 40.1 tokens/s, Running: 138 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 12.2%, CPU KV cache usage: 0.0%
INFO:     ::1:49722 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:58:08 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 40.0 tokens/s, Running: 137 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 12.3%, CPU KV cache usage: 0.0%
INFO:     ::1:49792 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:58:15 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 39.7 tokens/s, Running: 135 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 12.5%, CPU KV cache usage: 0.0%
INFO:     ::1:49632 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:58:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 39.2 tokens/s, Running: 134 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 12.8%, CPU KV cache usage: 0.0%
INFO:     ::1:49660 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49747 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:58:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.9 tokens/s, Running: 133 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 13.1%, CPU KV cache usage: 0.0%
INFO:     ::1:49740 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:58:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 56.3 tokens/s, Running: 131 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 13.3%, CPU KV cache usage: 0.0%
INFO:     ::1:49808 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:58:43 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 37.9 tokens/s, Running: 131 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 13.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:58:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.7 tokens/s, Running: 131 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 13.6%, CPU KV cache usage: 0.0%
INFO:     ::1:49950 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:58:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 48.8 tokens/s, Running: 130 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 13.6%, CPU KV cache usage: 0.0%
INFO 05-17 16:59:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 37.8 tokens/s, Running: 130 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 13.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:59:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.4 tokens/s, Running: 130 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 14.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:59:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 50.1 tokens/s, Running: 128 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 14.1%, CPU KV cache usage: 0.0%
INFO:     ::1:49618 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49764 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:59:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 37.3 tokens/s, Running: 128 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 14.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:59:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 37.3 tokens/s, Running: 127 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 14.8%, CPU KV cache usage: 0.0%
INFO:     ::1:49876 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49834 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49742 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49704 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:59:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 36.8 tokens/s, Running: 122 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 14.3%, CPU KV cache usage: 0.0%
INFO:     ::1:49850 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49620 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:59:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 36.1 tokens/s, Running: 122 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 14.3%, CPU KV cache usage: 0.0%
INFO 05-17 16:59:48 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 36.0 tokens/s, Running: 122 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 14.4%, CPU KV cache usage: 0.0%
INFO:     ::1:49716 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:59:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 35.8 tokens/s, Running: 120 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 14.4%, CPU KV cache usage: 0.0%
INFO:     ::1:49904 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:00:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 35.4 tokens/s, Running: 120 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 14.6%, CPU KV cache usage: 0.0%
INFO:     ::1:49908 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:00:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 35.2 tokens/s, Running: 119 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 14.8%, CPU KV cache usage: 0.0%
INFO 05-17 17:00:15 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 35.1 tokens/s, Running: 118 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 15.1%, CPU KV cache usage: 0.0%
INFO:     ::1:49794 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:00:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 35.0 tokens/s, Running: 116 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 15.2%, CPU KV cache usage: 0.0%
INFO:     ::1:49816 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49790 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:00:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 34.2 tokens/s, Running: 116 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 15.5%, CPU KV cache usage: 0.0%
INFO:     ::1:49756 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49974 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49640 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-17 17:00:32 worker_manager.py:344] Missed prefetch, fall back to loading delta 16 now
INFO 05-17 17:00:32 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 17:00:32 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112846)[0m WARNING 05-17 17:00:32 worker_manager.py:344] Missed prefetch, fall back to loading delta 16 now
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 17:00:32 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 17:00:32 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=112994)[0m WARNING 05-17 17:00:32 worker_manager.py:344] Missed prefetch, fall back to loading delta 16 now
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 17:00:32 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 17:00:32 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=113171)[0m WARNING 05-17 17:00:32 worker_manager.py:344] Missed prefetch, fall back to loading delta 16 now
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 17:00:32 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 17:00:32 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 17:00:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.6 tokens/s, Running: 114 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 17:00:47 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.179 seconds
[36m(RayWorkerVllm pid=113171)[0m INFO 05-17 17:00:47 worker_manager.py:364] Main thread loading delta 16 done
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 17:00:48 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.686 seconds
[36m(RayWorkerVllm pid=112846)[0m INFO 05-17 17:00:48 worker_manager.py:364] Main thread loading delta 16 done
INFO 05-17 17:00:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 114 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 17:00:49 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.933 seconds
[36m(RayWorkerVllm pid=112994)[0m INFO 05-17 17:00:49 worker_manager.py:364] Main thread loading delta 16 done
INFO 05-17 17:00:49 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.123 seconds
INFO 05-17 17:00:50 worker_manager.py:364] Main thread loading delta 16 done
INFO 05-17 17:00:56 metrics.py:276] Avg prompt throughput: 2.7 tokens/s, Avg generation throughput: 30.8 tokens/s, Running: 114 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.3%, CPU KV cache usage: 0.0%
INFO:     ::1:49884 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:01:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 34.8 tokens/s, Running: 112 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 14.9%, CPU KV cache usage: 0.0%
INFO:     ::1:49824 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49954 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:01:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.5 tokens/s, Running: 111 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.0%, CPU KV cache usage: 0.0%
INFO:     ::1:49888 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:01:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 47.5 tokens/s, Running: 110 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.2%, CPU KV cache usage: 0.0%
INFO 05-17 17:01:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 33.7 tokens/s, Running: 108 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.3%, CPU KV cache usage: 0.0%
INFO:     ::1:49852 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49880 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49894 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:01:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 33.2 tokens/s, Running: 106 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.4%, CPU KV cache usage: 0.0%
INFO:     ::1:49658 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:01:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 32.6 tokens/s, Running: 105 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.5%, CPU KV cache usage: 0.0%
INFO:     ::1:49996 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:01:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 32.4 tokens/s, Running: 104 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.5%, CPU KV cache usage: 0.0%
INFO:     ::1:49882 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49654 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49726 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:01:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 30.6 tokens/s, Running: 100 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.0%, CPU KV cache usage: 0.0%
INFO:     ::1:49848 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49694 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:50026 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:50016 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49622 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:01:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 30.5 tokens/s, Running: 96 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 14.6%, CPU KV cache usage: 0.0%
INFO:     ::1:49998 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49644 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:02:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 29.6 tokens/s, Running: 95 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 14.6%, CPU KV cache usage: 0.0%
INFO 05-17 17:02:08 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 29.5 tokens/s, Running: 94 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 14.7%, CPU KV cache usage: 0.0%
INFO:     ::1:49859 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:02:15 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 29.0 tokens/s, Running: 94 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.0%, CPU KV cache usage: 0.0%
INFO 05-17 17:02:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 29.2 tokens/s, Running: 94 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.3%, CPU KV cache usage: 0.0%
INFO 05-17 17:02:27 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 29.1 tokens/s, Running: 94 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.5%, CPU KV cache usage: 0.0%
INFO:     ::1:49636 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:02:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 29.1 tokens/s, Running: 93 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.5%, CPU KV cache usage: 0.0%
INFO 05-17 17:02:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.2 tokens/s, Running: 93 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.5%, CPU KV cache usage: 0.0%
INFO:     ::1:49932 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:02:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 36.1 tokens/s, Running: 92 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.5%, CPU KV cache usage: 0.0%
INFO 05-17 17:02:53 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 30.0 tokens/s, Running: 92 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.7%, CPU KV cache usage: 0.0%
INFO:     ::1:49892 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:02:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 29.8 tokens/s, Running: 91 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.5%, CPU KV cache usage: 0.0%
INFO 05-17 17:03:05 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 29.5 tokens/s, Running: 90 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.7%, CPU KV cache usage: 0.0%
INFO:     ::1:49752 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49710 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:03:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 29.0 tokens/s, Running: 89 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.8%, CPU KV cache usage: 0.0%
INFO:     ::1:49830 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:03:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.6 tokens/s, Running: 88 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.8%, CPU KV cache usage: 0.0%
INFO 05-17 17:03:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.8 tokens/s, Running: 88 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 16.0%, CPU KV cache usage: 0.0%
INFO:     ::1:50012 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:03:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.4 tokens/s, Running: 87 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.8%, CPU KV cache usage: 0.0%
INFO:     ::1:49846 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:03:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 37.6 tokens/s, Running: 86 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.8%, CPU KV cache usage: 0.0%
INFO 05-17 17:03:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.0 tokens/s, Running: 86 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.9%, CPU KV cache usage: 0.0%
INFO:     ::1:49612 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:03:48 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.9 tokens/s, Running: 85 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.9%, CPU KV cache usage: 0.0%
INFO 05-17 17:03:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.7 tokens/s, Running: 84 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 16.0%, CPU KV cache usage: 0.0%
INFO:     ::1:49842 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49914 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:04:00 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.3 tokens/s, Running: 81 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.7%, CPU KV cache usage: 0.0%
INFO:     ::1:49960 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49861 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:04:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.5 tokens/s, Running: 81 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.9%, CPU KV cache usage: 0.0%
INFO 05-17 17:04:13 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.6 tokens/s, Running: 79 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.7%, CPU KV cache usage: 0.0%
INFO:     ::1:50010 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:50014 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:04:19 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.0 tokens/s, Running: 78 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.5%, CPU KV cache usage: 0.0%
INFO:     ::1:49678 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49854 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:04:25 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.1 tokens/s, Running: 77 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.5%, CPU KV cache usage: 0.0%
INFO 05-17 17:04:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.3 tokens/s, Running: 76 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.4%, CPU KV cache usage: 0.0%
INFO:     ::1:50048 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49720 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:04:37 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.4 tokens/s, Running: 75 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.4%, CPU KV cache usage: 0.0%
INFO:     ::1:49672 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:04:43 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.6 tokens/s, Running: 74 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.5%, CPU KV cache usage: 0.0%
INFO:     ::1:49838 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:04:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.2 tokens/s, Running: 72 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.2%, CPU KV cache usage: 0.0%
INFO:     ::1:49934 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:04:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 24.8 tokens/s, Running: 72 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.4%, CPU KV cache usage: 0.0%
INFO 05-17 17:05:00 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 24.8 tokens/s, Running: 72 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.5%, CPU KV cache usage: 0.0%
INFO 05-17 17:05:06 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 24.4 tokens/s, Running: 72 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.6%, CPU KV cache usage: 0.0%
INFO 05-17 17:05:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 24.9 tokens/s, Running: 72 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.6%, CPU KV cache usage: 0.0%
INFO:     ::1:49760 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:05:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 24.6 tokens/s, Running: 71 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.6%, CPU KV cache usage: 0.0%
INFO:     ::1:49610 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:05:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 24.2 tokens/s, Running: 70 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.6%, CPU KV cache usage: 0.0%
INFO 05-17 17:05:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.8 tokens/s, Running: 70 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.8%, CPU KV cache usage: 0.0%
INFO 05-17 17:05:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 34.2 tokens/s, Running: 69 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.7%, CPU KV cache usage: 0.0%
INFO:     ::1:49696 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49772 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:05:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.7 tokens/s, Running: 67 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.5%, CPU KV cache usage: 0.0%
INFO:     ::1:50002 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49942 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:50042 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:05:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.8 tokens/s, Running: 65 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.2%, CPU KV cache usage: 0.0%
INFO 05-17 17:05:53 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.4 tokens/s, Running: 65 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.3%, CPU KV cache usage: 0.0%
INFO:     ::1:49734 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:05:58 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.3 tokens/s, Running: 63 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 14.9%, CPU KV cache usage: 0.0%
INFO:     ::1:49664 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49836 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:06:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.6 tokens/s, Running: 62 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 14.8%, CPU KV cache usage: 0.0%
INFO 05-17 17:06:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.5 tokens/s, Running: 61 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 14.8%, CPU KV cache usage: 0.0%
INFO:     ::1:49857 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:06:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.1 tokens/s, Running: 61 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.0%, CPU KV cache usage: 0.0%
INFO 05-17 17:06:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.1 tokens/s, Running: 61 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.1%, CPU KV cache usage: 0.0%
INFO:     ::1:49864 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49724 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:06:27 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 20.7 tokens/s, Running: 59 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 14.8%, CPU KV cache usage: 0.0%
INFO 05-17 17:06:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 20.4 tokens/s, Running: 59 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 14.9%, CPU KV cache usage: 0.0%
INFO 05-17 17:06:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 20.5 tokens/s, Running: 59 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.0%, CPU KV cache usage: 0.0%
INFO 05-17 17:06:45 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 20.5 tokens/s, Running: 59 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.0%, CPU KV cache usage: 0.0%
INFO 05-17 17:06:50 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 20.5 tokens/s, Running: 57 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 14.7%, CPU KV cache usage: 0.0%
INFO:     ::1:49748 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49896 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:06:56 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 20.8 tokens/s, Running: 57 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 14.8%, CPU KV cache usage: 0.0%
INFO:     ::1:49799 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:07:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 20.7 tokens/s, Running: 55 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 14.5%, CPU KV cache usage: 0.0%
INFO:     ::1:49878 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:07:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 20.0 tokens/s, Running: 53 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 14.1%, CPU KV cache usage: 0.0%
INFO:     ::1:49898 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:50018 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:07:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.4 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 14.0%, CPU KV cache usage: 0.0%
INFO:     ::1:49866 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:07:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.0 tokens/s, Running: 49 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 13.3%, CPU KV cache usage: 0.0%
INFO:     ::1:49766 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49964 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:49614 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:07:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.7 tokens/s, Running: 49 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 13.4%, CPU KV cache usage: 0.0%
INFO 05-17 17:07:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.9 tokens/s, Running: 49 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 13.4%, CPU KV cache usage: 0.0%
INFO 05-17 17:07:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.8 tokens/s, Running: 49 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 13.5%, CPU KV cache usage: 0.0%
                                                                                                                                                                                                                           