/mnt/hwfile/huqinghao/miniconda3/bin/python
2024-05-17 16:20:54,719 - INFO - Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2024-05-17 16:20:54,719 - INFO - Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-05-17 16:20:54,719 - INFO - NumExpr defaulting to 8 threads.
2024-05-17 16:20:56,334	INFO scripts.py:1182 -- Did not find any active Ray processes.

==========
== CUDA ==
==========

CUDA Version 12.1.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda8ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9450>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 05-17 16:21:09 api_server.py:191] vLLM API server version 0.3.3
INFO 05-17 16:21:09 api_server.py:192] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, lora_modules=[], delta_modules=[], swap_modules=[SwapModule(name='/vllm/.idea/full_models/Llama-2-13b-hf', local_path='/vllm/.idea/full_models/Llama-2-13b-hf'), SwapModule(name='delta-1', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-1'), SwapModule(name='delta-2', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-2'), SwapModule(name='delta-3', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-3'), SwapModule(name='delta-4', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-4'), SwapModule(name='delta-5', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-5'), SwapModule(name='delta-6', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-6'), SwapModule(name='delta-7', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-7'), SwapModule(name='delta-8', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-8'), SwapModule(name='delta-9', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-9'), SwapModule(name='delta-10', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-10'), SwapModule(name='delta-11', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-11'), SwapModule(name='delta-12', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-12'), SwapModule(name='delta-13', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-13'), SwapModule(name='delta-14', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-14'), SwapModule(name='delta-15', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-15'), SwapModule(name='delta-16', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-16'), SwapModule(name='delta-17', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-17'), SwapModule(name='delta-18', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-18'), SwapModule(name='delta-19', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-19'), SwapModule(name='delta-20', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-20'), SwapModule(name='delta-21', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-21'), SwapModule(name='delta-22', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-22'), SwapModule(name='delta-23', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-23'), SwapModule(name='delta-24', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-24'), SwapModule(name='delta-25', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-25'), SwapModule(name='delta-26', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-26'), SwapModule(name='delta-27', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-27'), SwapModule(name='delta-28', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-28'), SwapModule(name='delta-29', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-29'), SwapModule(name='delta-30', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-30'), SwapModule(name='delta-31', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-31'), SwapModule(name='delta-32', local_path='/vllm/.idea/full_models/Llama-2-13b-hf-32')], chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, seed=0, swap_space=4, gpu_memory_utilization=0.85, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=True, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=64, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=32, enable_delta=False, max_deltas=0, max_cpu_deltas=32, max_delta_bitwidth=4, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_prefetch=False, scheduler_policy='fcfs', max_swap_slots=6, max_cpu_models=9, enable_swap=True, engine_use_ray=False, disable_log_requests=True, max_log_len=None)
2024-05-17 16:21:12,960	INFO worker.py:1749 -- Started a local Ray instance.
INFO 05-17 16:21:15 llm_engine.py:90] Initializing an LLM engine (v0.3.3) with config: model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, lora_config=None, delta_config=None, swap_config=SwapConfig(max_packed_model=6, max_cpu_model=9), max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, seed=0)
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda92d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda82b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception ignored in: <function TempDirectory.__del__ at 0x7f00852d7eb0>
Traceback (most recent call last):
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
    self.remove()
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
    if self.temp_dir:
AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9d20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception ignored in: <function TempDirectory.__del__ at 0x7f00852d7eb0>
Traceback (most recent call last):
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
    self.remove()
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
    if self.temp_dir:
AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa5f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaaec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaac80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa3b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda84f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9480>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda8dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda8610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa200>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaaad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaaf50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaad10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9db0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda8580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9300>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda94e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda8e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda8250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda99f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa2c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaaef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa6e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda8910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa140>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaabf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddabc70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception ignored in: <function TempDirectory.__del__ at 0x7f00852d7eb0>
Traceback (most recent call last):
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
    self.remove()
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
    if self.temp_dir:
AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9840>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaae00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaaa70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa1a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777d9980a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa620>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaba60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaad10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda92d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddabb20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaada0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa980>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda86a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa0e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaab90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777d998520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9720>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddabe50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddabbb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa7a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777d9989a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa410>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddabc40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda8dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777d998340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9720>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda92d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaabf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa8c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab1f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777d998790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaaa10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddabcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777d998be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9750>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaac80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda86d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777d9992a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9a50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa320>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777d998820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9750>: Failed to establish a new connection: [Errno 111] Connection refused'))
BitBLAS Operator not loaded, retrying in 5 seconds...
Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
BitBLAS Operator not loaded, retrying in 5 seconds...
Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
BitBLAS Operator not loaded, retrying in 5 seconds...
Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/3dd68ac91b57f4a54cd30eb22c6181a40fa09b9532cfe4c4e5441e46261ec3fa/tvm_rt_mod'
INFO 05-17 16:36:49 selector.py:16] Using FlashAttention backend.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddabcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=99933)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7ee7921f6200>
[36m(RayWorkerVllm pid=99933)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=99933)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=99933)[0m     self.remove()
[36m(RayWorkerVllm pid=99933)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=99933)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=99933)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=100188)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f75a25ee200>
[36m(RayWorkerVllm pid=100188)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=100188)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=100188)[0m     self.remove()
[36m(RayWorkerVllm pid=100188)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=100188)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=100188)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=100188)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f75a25ee200>
[36m(RayWorkerVllm pid=100188)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=100188)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=100188)[0m     self.remove()
[36m(RayWorkerVllm pid=100188)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=100188)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=100188)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaaa10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaab90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9a80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa440>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa950>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaaef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda8af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9210>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9750>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda94b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaacb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa4a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777d9996f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda91e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda96c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda89a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda84c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddabfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9480>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaad10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaba60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777d998d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaa7a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddabbb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddabe50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda98a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777d999600>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9330>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9720>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddabd60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda90c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9db0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777d9983d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaaa10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddabcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777d999240>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda8eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda8df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda9510>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaafb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777d999ba0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddaba30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddab5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777ddabf70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda8c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777d998040>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=99933)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=99933)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=100188)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=100188)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=100188)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=100188)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=99715)[0m INFO 05-17 16:45:36 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=99933)[0m INFO 05-17 16:45:43 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=100188)[0m INFO 05-17 16:45:43 selector.py:16] Using FlashAttention backend.
INFO 05-17 16:45:57 model_runner.py:161] Loading model weights took 6.1114 GB
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda8eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f777dda8160>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=99715)[0m INFO 05-17 16:45:59 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=100188)[0m INFO 05-17 16:45:59 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=99933)[0m INFO 05-17 16:45:59 model_runner.py:161] Loading model weights took 6.1114 GB
INFO 05-17 16:46:12 ray_gpu_executor.py:275] # GPU blocks: 7008, # CPU blocks: 1310
INFO 05-17 16:46:15 block_manager.py:264] disable automatic prefix caching
WARNING 05-17 16:46:15 serving_chat.py:373] No chat template provided. Chat API will not work.
INFO:     Started server process [91415]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     ::1:58712 - "GET /sysinfo HTTP/1.1" 200 OK
Translating from base-model to /vllm/.idea/full_models/Llama-2-13b-hf
Warming up starts
{'id': 76, 'prompt': 'USER: Please write C++ code to read network packets from a socket on port 888\nASSISTANT:', 'timestamp': 0, 'model': 'delta-10', 'min_tokens': 380, 'max_tokens': 380}
Prefetching is disabled
INFO 05-17 16:46:25 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:46:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:46:45 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:46:50 models.py:164] Disk -> CPU: Loaded in 32.124 seconds
INFO 05-17 16:46:52 worker_manager.py:250] [1715935612.7576637] CPU -> GPU time: 2.4934
INFO 05-17 16:47:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=100188)[0m INFO 05-17 16:46:54 models.py:164] Disk -> CPU: Loaded in 36.691 seconds
[36m(RayWorkerVllm pid=99933)[0m INFO 05-17 16:46:56 models.py:164] Disk -> CPU: Loaded in 38.071 seconds
[36m(RayWorkerVllm pid=100188)[0m INFO 05-17 16:46:56 worker_manager.py:250] [1715935616.75999] CPU -> GPU time: 1.9275
[36m(RayWorkerVllm pid=99715)[0m INFO 05-17 16:46:58 models.py:164] Disk -> CPU: Loaded in 40.458 seconds
[36m(RayWorkerVllm pid=99933)[0m INFO 05-17 16:46:58 worker_manager.py:250] [1715935618.5328336] CPU -> GPU time: 2.3201
[36m(RayWorkerVllm pid=99715)[0m INFO 05-17 16:47:01 worker_manager.py:250] [1715935621.482013] CPU -> GPU time: 2.8821
INFO 05-17 16:47:06 metrics.py:276] Avg prompt throughput: 5.3 tokens/s, Avg generation throughput: 5.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:26 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:32 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:37 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-17 16:48:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-17 16:48:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO:     ::1:58714 - "POST /v1/completions HTTP/1.1" 200 OK
Warming up ends
Issuing queries
sending 1 queries at 0.2
sending 1 queries at 0.4
sending 1 queries at 0.5
sending 1 queries at 0.7000000000000001
sending 1 queries at 0.8
sending 1 queries at 0.9
sending 1 queries at 1.0
sending 1 queries at 1.4000000000000001
sending 2 queries at 2.0
sending 1 queries at 2.3000000000000003
sending 1 queries at 2.4000000000000004
sending 1 queries at 2.6
sending 4 queries at 3.0
sending 1 queries at 3.3000000000000003
sending 1 queries at 3.6
sending 1 queries at 3.9000000000000004
sending 1 queries at 4.6000000000000005
sending 1 queries at 4.800000000000001
sending 1 queries at 4.9
sending 2 queries at 5.2
sending 2 queries at 5.4
sending 1 queries at 5.9
sending 1 queries at 6.0
sending 2 queries at 6.1000000000000005
sending 1 queries at 6.4
sending 1 queries at 6.5
sending 2 queries at 6.6000000000000005
sending 1 queries at 6.800000000000001
sending 1 queries at 7.0
sending 1 queries at 7.1000000000000005
sending 1 queries at 7.6000000000000005
sending 1 queries at 7.800000000000001
sending 1 queries at 7.9
sending 1 queries at 8.0
sending 2 queries at 8.200000000000001
sending 1 queries at 8.4
sending 1 queries at 8.5
sending 2 queries at 8.6
sending 2 queries at 8.700000000000001
sending 1 queries at 8.9
sending 1 queries at 9.0
sending 2 queries at 9.700000000000001
sending 2 queries at 9.8
sending 2 queries at 10.0
sending 1 queries at 10.100000000000001
sending 3 queries at 10.200000000000001
sending 2 queries at 10.4
sending 2 queries at 10.5
sending 2 queries at 10.8
sending 2 queries at 11.200000000000001
sending 1 queries at 11.8
sending 1 queries at 11.9
sending 1 queries at 12.5
sending 1 queries at 12.700000000000001
sending 2 queries at 12.9
sending 3 queries at 13.0
sending 2 queries at 13.100000000000001
sending 2 queries at 13.200000000000001
sending 1 queries at 13.4
sending 2 queries at 13.600000000000001
sending 1 queries at 13.700000000000001
sending 1 queries at 13.8
sending 1 queries at 13.9
sending 1 queries at 14.3
sending 1 queries at 14.4
sending 2 queries at 14.600000000000001
sending 1 queries at 14.8
sending 2 queries at 14.9
sending 2 queries at 15.100000000000001
sending 2 queries at 15.4
sending 1 queries at 15.5
sending 1 queries at 15.600000000000001
sending 1 queries at 15.8
sending 2 queries at 16.400000000000002
sending 1 queries at 16.6
sending 1 queries at 16.7
sending 2 queries at 16.900000000000002
sending 1 queries at 17.400000000000002
sending 1 queries at 17.5
sending 1 queries at 17.8
sending 1 queries at 18.0
sending 1 queries at 18.1
sending 2 queries at 18.400000000000002
sending 1 queries at 18.8
sending 1 queries at 18.900000000000002
sending 1 queries at 19.3
sending 1 queries at 19.5
sending 1 queries at 19.700000000000003
sending 1 queries at 19.8
sending 1 queries at 20.3
sending 1 queries at 20.5
sending 1 queries at 20.6
sending 3 queries at 20.8
sending 1 queries at 21.0
sending 1 queries at 21.1
sending 1 queries at 21.200000000000003
sending 2 queries at 21.3
sending 1 queries at 21.400000000000002
sending 1 queries at 21.5
sending 1 queries at 21.700000000000003
sending 1 queries at 21.8
sending 1 queries at 22.0
sending 1 queries at 22.200000000000003
sending 1 queries at 22.3
sending 2 queries at 22.700000000000003
sending 1 queries at 22.8
sending 1 queries at 23.200000000000003
sending 1 queries at 23.5
sending 2 queries at 23.700000000000003
sending 1 queries at 24.1
sending 1 queries at 24.3
sending 1 queries at 25.400000000000002
sending 1 queries at 25.5
sending 2 queries at 25.8
sending 2 queries at 26.0
sending 1 queries at 26.3
sending 1 queries at 26.6
sending 2 queries at 26.8
sending 1 queries at 26.900000000000002
sending 1 queries at 27.0
sending 1 queries at 27.200000000000003
sending 1 queries at 27.400000000000002
sending 1 queries at 27.700000000000003
sending 1 queries at 28.3
sending 2 queries at 28.6
sending 1 queries at 28.700000000000003
sending 1 queries at 28.900000000000002
sending 1 queries at 29.0
sending 4 queries at 29.1
sending 2 queries at 29.400000000000002
sending 1 queries at 29.5
sending 1 queries at 30.0
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:48:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 1.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:48:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:48:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
total threads: 178
Prefetching is disabled
INFO 05-17 16:48:45 models.py:164] Disk -> CPU: Loaded in 33.570 seconds
INFO 05-17 16:48:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=99933)[0m INFO 05-17 16:48:50 models.py:164] Disk -> CPU: Loaded in 38.022 seconds
[36m(RayWorkerVllm pid=100188)[0m INFO 05-17 16:48:51 models.py:164] Disk -> CPU: Loaded in 39.665 seconds
[36m(RayWorkerVllm pid=99715)[0m INFO 05-17 16:48:52 models.py:164] Disk -> CPU: Loaded in 39.883 seconds
INFO 05-17 16:49:04 metrics.py:276] Avg prompt throughput: 2.1 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:49:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:49:24 models.py:164] Disk -> CPU: Loaded in 29.686 seconds
INFO 05-17 16:49:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=100188)[0m INFO 05-17 16:49:32 models.py:164] Disk -> CPU: Loaded in 38.064 seconds
INFO 05-17 16:49:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=99933)[0m INFO 05-17 16:49:37 models.py:164] Disk -> CPU: Loaded in 42.905 seconds
[36m(RayWorkerVllm pid=99715)[0m INFO 05-17 16:49:37 models.py:164] Disk -> CPU: Loaded in 43.289 seconds
INFO 05-17 16:49:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:49:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:03 models.py:164] Disk -> CPU: Loaded in 36.818 seconds
INFO 05-17 16:50:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=100188)[0m INFO 05-17 16:50:12 models.py:164] Disk -> CPU: Loaded in 37.556 seconds
INFO 05-17 16:50:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=99933)[0m INFO 05-17 16:50:19 models.py:164] Disk -> CPU: Loaded in 40.990 seconds
INFO 05-17 16:50:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=99715)[0m INFO 05-17 16:50:29 models.py:164] Disk -> CPU: Loaded in 49.408 seconds
INFO 05-17 16:50:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:50:41 models.py:164] Disk -> CPU: Loaded in 37.026 seconds
INFO 05-17 16:50:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=100188)[0m INFO 05-17 16:50:47 models.py:164] Disk -> CPU: Loaded in 33.604 seconds
[36m(RayWorkerVllm pid=99933)[0m INFO 05-17 16:50:52 models.py:164] Disk -> CPU: Loaded in 31.037 seconds
INFO 05-17 16:50:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=99715)[0m INFO 05-17 16:51:00 models.py:164] Disk -> CPU: Loaded in 28.305 seconds
INFO 05-17 16:51:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:22 models.py:164] Disk -> CPU: Loaded in 39.906 seconds
INFO 05-17 16:51:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=100188)[0m INFO 05-17 16:51:25 models.py:164] Disk -> CPU: Loaded in 35.916 seconds
[36m(RayWorkerVllm pid=99933)[0m INFO 05-17 16:51:31 models.py:164] Disk -> CPU: Loaded in 37.684 seconds
[36m(RayWorkerVllm pid=99715)[0m INFO 05-17 16:51:33 models.py:164] Disk -> CPU: Loaded in 29.710 seconds
INFO 05-17 16:51:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 98 reqs, Swapped: 0 reqs, Pending: 80 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
INFO:     ::1:59052 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:51:40 metrics.py:276] Avg prompt throughput: 830.1 tokens/s, Avg generation throughput: 88.2 tokens/s, Running: 101 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 5.4%, CPU KV cache usage: 0.0%
INFO:     ::1:59082 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59048 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59093 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59096 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59100 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59380 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59188 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59426 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:51:45 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 107.6 tokens/s, Running: 94 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 5.5%, CPU KV cache usage: 0.0%
INFO:     ::1:59432 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59044 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59272 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59372 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:51:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 101.3 tokens/s, Running: 91 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 6.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:56 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 95.0 tokens/s, Running: 89 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 6.4%, CPU KV cache usage: 0.0%
INFO:     ::1:59216 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59276 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59120 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59312 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 96.7 tokens/s, Running: 86 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 6.6%, CPU KV cache usage: 0.0%
INFO:     ::1:59110 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59392 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59074 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 93.1 tokens/s, Running: 83 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 7.1%, CPU KV cache usage: 0.0%
INFO:     ::1:59056 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59278 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:13 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 89.3 tokens/s, Running: 82 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 7.2%, CPU KV cache usage: 0.0%
INFO:     ::1:59042 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59069 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 88.3 tokens/s, Running: 79 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 7.6%, CPU KV cache usage: 0.0%
INFO:     ::1:59152 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59144 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 86.5 tokens/s, Running: 78 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 7.9%, CPU KV cache usage: 0.0%
INFO:     ::1:59342 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 84.2 tokens/s, Running: 77 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.1%, CPU KV cache usage: 0.0%
INFO:     ::1:59031 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59168 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 83.1 tokens/s, Running: 75 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.6%, CPU KV cache usage: 0.0%
INFO:     ::1:59254 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59032 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:40 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 80.4 tokens/s, Running: 73 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.4%, CPU KV cache usage: 0.0%
INFO:     ::1:59122 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59308 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 79.7 tokens/s, Running: 71 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.5%, CPU KV cache usage: 0.0%
INFO:     ::1:59196 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59220 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59194 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 75.6 tokens/s, Running: 68 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.8%, CPU KV cache usage: 0.0%
INFO:     ::1:59162 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59291 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59228 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59350 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 81.0 tokens/s, Running: 64 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.4%, CPU KV cache usage: 0.0%
INFO:     ::1:59292 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59256 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59296 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:53:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 79.9 tokens/s, Running: 61 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.6%, CPU KV cache usage: 0.0%
INFO:     ::1:59289 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59132 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59062 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59250 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59034 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59414 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59424 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:53:08 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 73.5 tokens/s, Running: 53 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 7.9%, CPU KV cache usage: 0.0%
INFO:     ::1:59386 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:53:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 65.8 tokens/s, Running: 53 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.3%, CPU KV cache usage: 0.0%
INFO 05-17 16:53:19 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 67.8 tokens/s, Running: 53 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.6%, CPU KV cache usage: 0.0%
INFO:     ::1:59294 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:53:25 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 67.6 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.6%, CPU KV cache usage: 0.0%
INFO:     ::1:59158 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59118 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59236 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:53:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 62.6 tokens/s, Running: 49 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.6%, CPU KV cache usage: 0.0%
INFO 05-17 16:53:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 61.2 tokens/s, Running: 48 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.6%, CPU KV cache usage: 0.0%
INFO:     ::1:59024 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:53:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 61.5 tokens/s, Running: 48 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 9.0%, CPU KV cache usage: 0.0%
INFO:     ::1:59084 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59258 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:53:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 60.6 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.9%, CPU KV cache usage: 0.0%
INFO:     ::1:59076 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59242 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:53:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 57.4 tokens/s, Running: 43 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.7%, CPU KV cache usage: 0.0%
INFO:     ::1:59322 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:53:58 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 53.9 tokens/s, Running: 43 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 9.0%, CPU KV cache usage: 0.0%
INFO:     ::1:59164 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59022 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 53.4 tokens/s, Running: 41 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.9%, CPU KV cache usage: 0.0%
INFO:     ::1:59176 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59394 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 50.4 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.8%, CPU KV cache usage: 0.0%
INFO:     ::1:59140 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59240 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 44.0 tokens/s, Running: 37 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.6%, CPU KV cache usage: 0.0%
INFO:     ::1:59260 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59130 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:19 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 49.5 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.5%, CPU KV cache usage: 0.0%
INFO 05-17 16:54:25 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 43.7 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.6%, CPU KV cache usage: 0.0%
INFO:     ::1:59298 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 43.1 tokens/s, Running: 33 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.4%, CPU KV cache usage: 0.0%
INFO:     ::1:59416 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59270 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59170 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59026 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 40.3 tokens/s, Running: 30 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 7.9%, CPU KV cache usage: 0.0%
INFO 05-17 16:54:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 37.8 tokens/s, Running: 30 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 8.1%, CPU KV cache usage: 0.0%
INFO:     ::1:59186 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 36.9 tokens/s, Running: 29 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 7.8%, CPU KV cache usage: 0.0%
INFO:     ::1:59134 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 36.1 tokens/s, Running: 28 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 7.6%, CPU KV cache usage: 0.0%
INFO:     ::1:59126 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59174 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:58 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 34.4 tokens/s, Running: 26 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 7.4%, CPU KV cache usage: 0.0%
INFO:     ::1:59160 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59212 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59198 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:55:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 30.5 tokens/s, Running: 23 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 6.7%, CPU KV cache usage: 0.0%
INFO 05-17 16:55:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.8 tokens/s, Running: 23 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 6.9%, CPU KV cache usage: 0.0%
INFO:     ::1:59038 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:55:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.1 tokens/s, Running: 22 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 6.7%, CPU KV cache usage: 0.0%
INFO 05-17 16:55:19 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 30.6 tokens/s, Running: 22 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 6.9%, CPU KV cache usage: 0.0%
INFO 05-17 16:55:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.1 tokens/s, Running: 22 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 7.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:55:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.1 tokens/s, Running: 22 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 7.1%, CPU KV cache usage: 0.0%
INFO:     ::1:59402 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59274 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:55:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.0 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 6.4%, CPU KV cache usage: 0.0%
INFO:     ::1:59090 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:59060 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:55:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 24.9 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 5.9%, CPU KV cache usage: 0.0%
INFO 05-17 16:55:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.6 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 74 reqs, GPU KV cache usage: 6.1%, CPU KV cache usage: 0.0%
                                                                                             