/mnt/hwfile/huqinghao/miniconda3/bin/python
2024-05-17 16:20:54,682 - INFO - Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2024-05-17 16:20:54,682 - INFO - Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-05-17 16:20:54,682 - INFO - NumExpr defaulting to 8 threads.
2024-05-17 16:20:56,311	INFO scripts.py:1182 -- Did not find any active Ray processes.

==========
== CUDA ==
==========

CUDA Version 12.1.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed450>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 05-17 16:21:11 api_server.py:191] vLLM API server version 0.3.3
INFO 05-17 16:21:11 api_server.py:192] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, lora_modules=[], delta_modules=[Delta(name='delta-1', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1'), Delta(name='delta-2', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2'), Delta(name='delta-3', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3'), Delta(name='delta-4', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4'), Delta(name='delta-5', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5'), Delta(name='delta-6', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6'), Delta(name='delta-7', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7'), Delta(name='delta-8', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8'), Delta(name='delta-9', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-9'), Delta(name='delta-10', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-10'), Delta(name='delta-11', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-11'), Delta(name='delta-12', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-12'), Delta(name='delta-13', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-13'), Delta(name='delta-14', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-14'), Delta(name='delta-15', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-15'), Delta(name='delta-16', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-16'), Delta(name='delta-17', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-17'), Delta(name='delta-18', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-18'), Delta(name='delta-19', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-19'), Delta(name='delta-20', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-20'), Delta(name='delta-21', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-21'), Delta(name='delta-22', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-22'), Delta(name='delta-23', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-23'), Delta(name='delta-24', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-24'), Delta(name='delta-25', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-25'), Delta(name='delta-26', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-26'), Delta(name='delta-27', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-27'), Delta(name='delta-28', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-28'), Delta(name='delta-29', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-29'), Delta(name='delta-30', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-30'), Delta(name='delta-31', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-31'), Delta(name='delta-32', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-32')], swap_modules=[], chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, seed=0, swap_space=4, gpu_memory_utilization=0.85, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=True, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=64, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=32, enable_delta=True, max_deltas=24, max_cpu_deltas=32, max_delta_bitwidth=4, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_prefetch=False, scheduler_policy='fcfs', max_swap_slots=1, max_cpu_models=4, enable_swap=False, engine_use_ray=False, disable_log_requests=True, max_log_len=None)
2024-05-17 16:21:14,499	INFO worker.py:1749 -- Started a local Ray instance.
INFO 05-17 16:21:16 llm_engine.py:90] Initializing an LLM engine (v0.3.3) with config: model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, lora_config=None, delta_config=DeltaConfig(max_deltas=24, max_bitwidth=4, delta_dtype=torch.int8, max_cpu_deltas=32, delta_extra_vocab_size=0, pack_factor=Fraction(2, 1), kernel=<QuantKernel.TRITON: 'triton'>), swap_config=None, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, seed=0)
INFO 05-17 16:21:16 llm_engine.py:243] ignored verifying delta_config
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fedd20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fecf70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee5f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feeec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fc7b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee860>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fedf90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fecdc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fedc90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed0c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec1f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feea40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fc79d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee470>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed210>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fedba0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fedd50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed450>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec190>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee200>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feeec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed8a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed6c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee290>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9c0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fecd90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fecfa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fedc90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fc7850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fefd30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef970>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fedae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed4b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee050>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed780>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9c4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fefdc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed6f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fedcf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed840>: Failed to establish a new connection: [Errno 111] Connection refused'))
Using bitblas
WARNING 05-17 16:31:02 models.py:48] Using bitblas delta modules
INFO 05-17 16:31:02 selector.py:16] Using FlashAttention backend.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=40669)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f61f9116200>
[36m(RayWorkerVllm pid=40669)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=40669)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=40669)[0m     self.remove()
[36m(RayWorkerVllm pid=40669)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=40669)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=40669)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=40938)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7fa59850a200>
[36m(RayWorkerVllm pid=40938)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=40938)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=40938)[0m     self.remove()
[36m(RayWorkerVllm pid=40938)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=40938)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=40938)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=40669)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f61f9116200>
[36m(RayWorkerVllm pid=40669)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=40669)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=40669)[0m     self.remove()
[36m(RayWorkerVllm pid=40669)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=40669)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=40669)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9c9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fecd60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed810>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9c310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fefca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fefa90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed960>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fedf00>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=41094)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f4df59f2200>
[36m(RayWorkerVllm pid=41094)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=41094)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=41094)[0m     self.remove()
[36m(RayWorkerVllm pid=41094)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=41094)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=41094)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9c790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fedcc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9cbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feffa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed6f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fedcf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed840>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9d2a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed390>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed180>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feda80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feeda0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9c820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feffd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fedb10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9cf10>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=40938)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7fa59850a200>
[36m(RayWorkerVllm pid=40938)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=40938)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=40938)[0m     self.remove()
[36m(RayWorkerVllm pid=40938)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=40938)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=40938)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fece50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feceb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fefcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fedd50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec490>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9d660>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feceb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fc7af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee3b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feeb60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed990>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9c310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed180>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feda80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feeda0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee230>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9d720>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fefd60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fefb80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef760>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9dba0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feceb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9d000>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee380>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed1b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fedd20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fefa60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9d8a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fed180>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feda80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feeda0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee230>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9dde0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fee290>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feda50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fedd80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fec8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13c9e470>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13feceb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=40669)[0m Using bitblas
[36m(RayWorkerVllm pid=40938)[0m Using bitblas
[36m(RayWorkerVllm pid=41094)[0m Using bitblas
[36m(RayWorkerVllm pid=40669)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=40669)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=40938)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=40938)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=40669)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=40669)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=41094)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=41094)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/b4a25346c74288d991fa81fa1e3d91528a819486b20d89733d055fad009dfa00/tvm_rt_mod'
[36m(RayWorkerVllm pid=40938)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=40938)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/4568e30b459050661831f4c929775cbd5413026a83e7ff243159971a8cb3ed07/tvm_rt_mod'
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:40:01 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:40:02 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:41:42 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:41:42 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:45:40 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:45:40 selector.py:16] Using FlashAttention backend.
INFO 05-17 16:46:09 model_runner.py:161] Loading model weights took 6.1114 GB
INFO 05-17 16:46:09 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:46:09 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:46:09 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:46:11 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:46:11 worker_manager.py:297] Starting prefetching thread
WARNING 05-17 16:46:13 quant_linear_triton.py:557] We should warm up the kernel here 
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba13fef640>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:46:13 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:46:14 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:46:14 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:46:14 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:46:17 quant_linear_triton.py:557] We should warm up the kernel here 
INFO 05-17 16:46:30 ray_gpu_executor.py:275] # GPU blocks: 6431, # CPU blocks: 1310
INFO 05-17 16:46:33 scheduler.py:136] Using fcfs policy.
INFO 05-17 16:46:33 block_manager.py:264] disable automatic prefix caching
WARNING 05-17 16:46:33 serving_chat.py:373] No chat template provided. Chat API will not work.
INFO:     Started server process [32669]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     ::1:34848 - "GET /sysinfo HTTP/1.1" 200 OK
Translating from base-model to /vllm/.idea/full_models/Llama-2-13b-hf
Warming up starts
{'id': 40, 'prompt': "USER: ok so i missed doomer. what's the next big thing that will make me rich?\nASSISTANT:", 'timestamp': 0, 'model': 'delta-6', 'min_tokens': 66, 'max_tokens': 66}
Prefetching is disabled
WARNING 05-17 16:46:38 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
INFO 05-17 16:46:38 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:46:38 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:46:38 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:46:38 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:46:38 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:46:38 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:46:38 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:46:38 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:46:38 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:46:38 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:46:38 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:46:43 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:46:52 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.484 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:46:52 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:46:52 worker_manager.py:379] [1715935612.8496296] activating delta
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:46:52 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.671 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:46:53 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:46:53 worker_manager.py:379] [1715935613.04006] activating delta
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:46:52 worker_manager.py:384] [1715935612.98424] CPU -> GPU time: 0.1346
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:46:53 worker_manager.py:384] [1715935613.1731458] CPU -> GPU time: 0.1330
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:46:53 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.182 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:46:53 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:46:53 worker_manager.py:379] [1715935613.5528312] activating delta
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:46:53 worker_manager.py:384] [1715935613.6865566] CPU -> GPU time: 0.1337
INFO 05-17 16:46:53 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:46:55 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.231 seconds
INFO 05-17 16:46:55 worker_manager.py:364] Main thread loading delta 6 done
INFO 05-17 16:46:55 worker_manager.py:379] [1715935615.5966516] activating delta
INFO 05-17 16:46:55 worker_manager.py:384] [1715935615.6982722] CPU -> GPU time: 0.1016
INFO 05-17 16:46:58 metrics.py:276] Avg prompt throughput: 5.7 tokens/s, Avg generation throughput: 2.2 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO:     ::1:34850 - "POST /v1/completions HTTP/1.1" 200 OK
Warming up ends
Issuing queries
sending 1 queries at 0.30000000000000004
sending 1 queries at 0.7000000000000001
sending 1 queries at 1.0
sending 1 queries at 1.3
sending 1 queries at 1.5
sending 1 queries at 1.8
sending 1 queries at 2.0
sending 1 queries at 2.8000000000000003
sending 1 queries at 3.9000000000000004
sending 1 queries at 4.0
sending 1 queries at 4.6000000000000005
sending 1 queries at 4.800000000000001
sending 1 queries at 5.1000000000000005
sending 4 queries at 6.0
sending 1 queries at 6.6000000000000005
sending 1 queries at 7.1000000000000005
sending 1 queries at 7.800000000000001
sending 1 queries at 9.1
sending 1 queries at 9.600000000000001
sending 1 queries at 9.8
sending 1 queries at 10.3
sending 1 queries at 10.4
sending 1 queries at 10.700000000000001
sending 1 queries at 10.8
sending 1 queries at 11.700000000000001
sending 1 queries at 12.0
sending 1 queries at 12.100000000000001
sending 1 queries at 12.200000000000001
sending 1 queries at 12.700000000000001
sending 1 queries at 12.9
sending 2 queries at 13.200000000000001
sending 1 queries at 13.600000000000001
sending 1 queries at 13.9
sending 1 queries at 14.200000000000001
sending 1 queries at 15.100000000000001
sending 1 queries at 15.5
sending 1 queries at 15.700000000000001
sending 1 queries at 15.9
sending 2 queries at 16.3
sending 1 queries at 16.7
sending 1 queries at 17.0
sending 2 queries at 17.1
sending 1 queries at 17.3
sending 1 queries at 17.400000000000002
sending 1 queries at 17.7
sending 1 queries at 17.900000000000002
sending 2 queries at 19.400000000000002
sending 1 queries at 19.5
sending 1 queries at 19.6
sending 1 queries at 19.900000000000002
sending 1 queries at 20.0
sending 1 queries at 20.200000000000003
sending 1 queries at 20.3
sending 2 queries at 20.400000000000002
sending 2 queries at 20.8
sending 1 queries at 20.900000000000002
sending 1 queries at 21.0
sending 2 queries at 21.6
sending 2 queries at 22.3
sending 1 queries at 23.5
sending 1 queries at 23.700000000000003
sending 1 queries at 25.0
sending 1 queries at 25.3
sending 2 queries at 25.8
sending 2 queries at 25.900000000000002
sending 1 queries at 26.0
sending 1 queries at 26.1
sending 1 queries at 26.200000000000003
sending 2 queries at 26.400000000000002
sending 1 queries at 26.8
sending 1 queries at 27.1
sending 1 queries at 27.200000000000003
sending 1 queries at 27.400000000000002
sending 1 queries at 27.5
sending 1 queries at 27.8
sending 1 queries at 28.6
sending 1 queries at 28.8
sending 1 queries at 29.1
sending 1 queries at 29.200000000000003
sending 1 queries at 29.6
sending 1 queries at 29.700000000000003
sending 1 queries at 29.8
Prefetching is disabled
Prefetching is disabled
WARNING 05-17 16:47:13 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
INFO 05-17 16:47:13 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:47:13 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:47:13 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:47:13 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:47:13 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:47:13 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:47:13 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:47:13 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:47:13 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:47:13 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:47:13 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:47:23 metrics.py:276] Avg prompt throughput: 1.4 tokens/s, Avg generation throughput: 1.2 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:47:25 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.575 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:47:25 worker_manager.py:364] Main thread loading delta 22 done
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:47:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.479 seconds
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:47:28 worker_manager.py:364] Main thread loading delta 22 done
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:47:30 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.947 seconds
INFO 05-17 16:47:30 worker_manager.py:364] Main thread loading delta 22 done
Prefetching is disabled
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:47:30 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.206 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:47:30 worker_manager.py:364] Main thread loading delta 22 done
Prefetching is disabled
INFO 05-17 16:47:31 metrics.py:276] Avg prompt throughput: 3.1 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
WARNING 05-17 16:47:31 worker_manager.py:344] Missed prefetch, fall back to loading delta 32 now
INFO 05-17 16:47:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:47:31 models.py:263] [main] Lossless Compression Disabled
total threads: 96
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:47:31 worker_manager.py:344] Missed prefetch, fall back to loading delta 32 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:47:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:47:31 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:47:31 worker_manager.py:344] Missed prefetch, fall back to loading delta 32 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:47:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:47:31 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:47:31 worker_manager.py:344] Missed prefetch, fall back to loading delta 32 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:47:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:47:31 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 16:47:43 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:47:48 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.225 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:47:48 worker_manager.py:364] Main thread loading delta 32 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:47:48 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:47:48 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:47:48 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:47:49 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.159 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:47:49 worker_manager.py:364] Main thread loading delta 32 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:47:49 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:47:49 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:47:49 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:47:49 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.618 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:47:49 worker_manager.py:364] Main thread loading delta 32 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:47:49 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:47:49 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:47:49 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:47:53 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:47:55 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 24.170 seconds
INFO 05-17 16:47:55 worker_manager.py:364] Main thread loading delta 32 done
WARNING 05-17 16:47:55 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
INFO 05-17 16:47:55 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:47:55 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:02 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.796 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:02 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:48:02 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:02 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:02 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:02 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.174 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:02 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:48:02 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:02 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:02 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:48:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:06 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.380 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:06 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:48:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:06 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:48:12 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.133 seconds
INFO 05-17 16:48:12 worker_manager.py:364] Main thread loading delta 1 done
WARNING 05-17 16:48:12 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
INFO 05-17 16:48:12 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:48:12 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:48:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:17 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.714 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:17 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:48:17 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:17 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:17 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:19 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.258 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:19 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:48:19 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:19 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:19 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:48:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:25 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 22.148 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:25 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:48:25 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:25 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:25 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:26 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 8.868 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:26 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:48:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:26 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:48:30 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.325 seconds
INFO 05-17 16:48:30 worker_manager.py:364] Main thread loading delta 2 done
WARNING 05-17 16:48:30 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
INFO 05-17 16:48:30 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:48:30 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:48:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:35 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.279 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:35 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:48:35 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:35 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:35 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:35 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.593 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:35 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:48:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:36 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:48:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 8.878 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:44 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:48:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:44 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:45 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.918 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:45 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:48:45 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:45 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:48:45 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:48:45 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.635 seconds
INFO 05-17 16:48:45 worker_manager.py:364] Main thread loading delta 3 done
WARNING 05-17 16:48:46 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
INFO 05-17 16:48:46 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:48:46 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:48:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:55 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.027 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:55 worker_manager.py:364] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:48:55 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:56 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:48:56 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:56 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 20.674 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:56 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:48:57 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:57 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:48:57 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:48:59 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.572 seconds
INFO 05-17 16:48:59 worker_manager.py:364] Main thread loading delta 4 done
WARNING 05-17 16:48:59 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
INFO 05-17 16:48:59 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:48:59 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:00 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.848 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:00 worker_manager.py:364] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:49:00 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:00 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:00 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:49:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:04 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 8.504 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:04 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:49:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:04 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:13 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.170 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:13 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:49:14 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:14 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:14 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:49:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:15 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.379 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:15 worker_manager.py:364] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:49:15 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:15 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:15 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:49:18 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.997 seconds
INFO 05-17 16:49:18 worker_manager.py:364] Main thread loading delta 5 done
WARNING 05-17 16:49:19 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
INFO 05-17 16:49:19 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:49:19 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:20 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.349 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:20 worker_manager.py:364] Main thread loading delta 9 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:49:20 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:20 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:20 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:49:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:24 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.283 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:24 worker_manager.py:364] Main thread loading delta 9 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:49:24 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:24 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:24 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 8.106 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:28 worker_manager.py:364] Main thread loading delta 10 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:49:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:28 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:32 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.995 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:32 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:49:32 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:32 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:32 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:49:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:49:35 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.832 seconds
INFO 05-17 16:49:35 worker_manager.py:364] Main thread loading delta 7 done
WARNING 05-17 16:49:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
INFO 05-17 16:49:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:49:36 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.422 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:40 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:49:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:40 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.956 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:42 worker_manager.py:364] Main thread loading delta 10 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:49:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:42 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:49:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:45 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.778 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:45 worker_manager.py:364] Main thread loading delta 9 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:49:45 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:45 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:45 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:49:51 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.594 seconds
INFO 05-17 16:49:51 worker_manager.py:364] Main thread loading delta 9 done
WARNING 05-17 16:49:51 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
INFO 05-17 16:49:51 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:49:51 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:49:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:55 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.140 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:55 worker_manager.py:364] Main thread loading delta 13 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:49:55 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:55 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:49:55 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:56 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.679 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:56 worker_manager.py:364] Main thread loading delta 10 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:49:56 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:56 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:49:56 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:59 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.337 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:59 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:49:59 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:59 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:49:59 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:50:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:11 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.553 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:11 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:50:11 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:11 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:11 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:50:13 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 21.674 seconds
INFO 05-17 16:50:13 worker_manager.py:364] Main thread loading delta 10 done
WARNING 05-17 16:50:13 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
INFO 05-17 16:50:13 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:50:13 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:50:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:50:15 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 19.454 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:50:15 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:50:15 worker_manager.py:344] Missed prefetch, fall back to loading delta 15 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:50:15 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:50:15 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:50:15 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.349 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:50:15 worker_manager.py:364] Main thread loading delta 13 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:50:15 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:50:15 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:50:15 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:50:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:50:25 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 9.710 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:50:25 worker_manager.py:364] Main thread loading delta 15 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:50:25 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:50:25 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:50:25 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:27 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.056 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:27 worker_manager.py:364] Main thread loading delta 13 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:50:27 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:27 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:27 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:50:32 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 19.040 seconds
INFO 05-17 16:50:32 worker_manager.py:364] Main thread loading delta 11 done
WARNING 05-17 16:50:32 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
INFO 05-17 16:50:32 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:50:32 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:50:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:50:34 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.479 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:50:34 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:50:34 worker_manager.py:344] Missed prefetch, fall back to loading delta 15 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:50:34 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:50:34 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:39 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.938 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:39 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:50:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 15 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:40 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:50:43 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 9.319 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:50:43 worker_manager.py:364] Main thread loading delta 15 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:50:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:50:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:50:44 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:50:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:50:45 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 20.480 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:50:45 worker_manager.py:364] Main thread loading delta 17 done
INFO 05-17 16:50:48 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.148 seconds
INFO 05-17 16:50:48 worker_manager.py:364] Main thread loading delta 13 done
WARNING 05-17 16:50:48 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
INFO 05-17 16:50:48 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:50:48 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:50 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.486 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:50 worker_manager.py:364] Main thread loading delta 15 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:50:50 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:50 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:50 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:50:52 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.957 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:50:52 worker_manager.py:364] Main thread loading delta 17 done
INFO 05-17 16:50:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 6.715 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:50:57 worker_manager.py:364] Main thread loading delta 17 done
INFO 05-17 16:50:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 9.722 seconds
INFO 05-17 16:50:58 worker_manager.py:364] Main thread loading delta 14 done
WARNING 05-17 16:50:58 worker_manager.py:344] Missed prefetch, fall back to loading delta 15 now
INFO 05-17 16:50:58 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:50:58 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:51:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:51:05 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.565 seconds
INFO 05-17 16:51:05 worker_manager.py:364] Main thread loading delta 15 done
WARNING 05-17 16:51:05 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
INFO 05-17 16:51:05 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:51:05 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:51:12 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 6.424 seconds
INFO 05-17 16:51:12 worker_manager.py:364] Main thread loading delta 17 done
INFO 05-17 16:51:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 52 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
INFO:     ::1:34976 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-17 16:51:17 worker_manager.py:344] Missed prefetch, fall back to loading delta 12 now
INFO 05-17 16:51:17 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:51:17 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:51:17 worker_manager.py:344] Missed prefetch, fall back to loading delta 12 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:51:17 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:51:17 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:51:17 worker_manager.py:344] Missed prefetch, fall back to loading delta 12 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:51:17 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:51:17 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:51:17 worker_manager.py:344] Missed prefetch, fall back to loading delta 12 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:51:17 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:51:17 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:51:24 metrics.py:276] Avg prompt throughput: 135.9 tokens/s, Avg generation throughput: 5.0 tokens/s, Running: 95 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:51:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.749 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:51:28 worker_manager.py:364] Main thread loading delta 12 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:51:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:51:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:51:28 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:51:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 95 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:51:35 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.260 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:51:35 worker_manager.py:364] Main thread loading delta 12 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:51:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:51:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:51:36 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:51:37 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 20.170 seconds
INFO 05-17 16:51:37 worker_manager.py:364] Main thread loading delta 12 done
WARNING 05-17 16:51:37 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
INFO 05-17 16:51:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:51:37 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:51:39 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.213 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:51:39 worker_manager.py:364] Main thread loading delta 18 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:51:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 19 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:51:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:51:39 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:51:43 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.591 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:51:43 worker_manager.py:364] Main thread loading delta 18 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:51:43 worker_manager.py:344] Missed prefetch, fall back to loading delta 19 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:51:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:51:43 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:51:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 95 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:51:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 29.102 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:51:46 worker_manager.py:364] Main thread loading delta 12 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:51:46 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:51:46 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:51:46 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:51:47 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.826 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:51:47 worker_manager.py:364] Main thread loading delta 19 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:51:47 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:51:48 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:51:48 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:51:49 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.120 seconds
INFO 05-17 16:51:49 worker_manager.py:364] Main thread loading delta 18 done
WARNING 05-17 16:51:49 worker_manager.py:344] Missed prefetch, fall back to loading delta 19 now
INFO 05-17 16:51:49 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:51:49 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:51:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 95 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:51:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.399 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:51:57 worker_manager.py:364] Main thread loading delta 19 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:51:57 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:51:57 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:51:57 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:52:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 95 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:52:04 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.866 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:52:04 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=40938)[0m WARNING 05-17 16:52:05 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:52:05 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:52:05 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:52:06 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.676 seconds
INFO 05-17 16:52:06 worker_manager.py:364] Main thread loading delta 19 done
WARNING 05-17 16:52:07 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
INFO 05-17 16:52:07 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:52:07 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:52:07 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.275 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:52:07 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=40669)[0m WARNING 05-17 16:52:07 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:52:07 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:52:07 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:52:10 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 24.037 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:52:10 worker_manager.py:364] Main thread loading delta 18 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:52:11 worker_manager.py:344] Missed prefetch, fall back to loading delta 19 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:52:11 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:52:11 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:52:11 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 6.147 seconds
[36m(RayWorkerVllm pid=40938)[0m INFO 05-17 16:52:11 worker_manager.py:364] Main thread loading delta 26 done
INFO 05-17 16:52:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 95 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:52:18 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.231 seconds
[36m(RayWorkerVllm pid=40669)[0m INFO 05-17 16:52:18 worker_manager.py:364] Main thread loading delta 26 done
INFO 05-17 16:52:18 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.449 seconds
INFO 05-17 16:52:18 worker_manager.py:364] Main thread loading delta 20 done
WARNING 05-17 16:52:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
INFO 05-17 16:52:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 16:52:18 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:52:20 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 9.506 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:52:20 worker_manager.py:364] Main thread loading delta 19 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:52:20 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:52:20 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:52:20 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 16:52:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 95 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:52:26 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.656 seconds
INFO 05-17 16:52:26 worker_manager.py:364] Main thread loading delta 26 done
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:52:26 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 5.931 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:52:26 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=41094)[0m WARNING 05-17 16:52:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:52:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:52:26 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:52:31 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 4.480 seconds
[36m(RayWorkerVllm pid=41094)[0m INFO 05-17 16:52:31 worker_manager.py:364] Main thread loading delta 26 done
INFO 05-17 16:52:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 95 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:52:39 metrics.py:276] Avg prompt throughput: 345.0 tokens/s, Avg generation throughput: 27.5 tokens/s, Running: 94 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO:     ::1:35016 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:45 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 30.8 tokens/s, Running: 94 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO:     ::1:34960 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35006 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 30.4 tokens/s, Running: 88 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO:     ::1:35160 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35022 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35026 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35024 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35020 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:52:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 30.0 tokens/s, Running: 87 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO:     ::1:35132 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35140 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35040 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:53:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 29.2 tokens/s, Running: 84 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO:     ::1:35028 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:53:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.6 tokens/s, Running: 82 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO:     ::1:34956 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:53:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.7 tokens/s, Running: 82 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:53:20 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 38.4 tokens/s, Running: 82 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.6%, CPU KV cache usage: 0.0%
INFO 05-17 16:53:26 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.2 tokens/s, Running: 82 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:53:32 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.2 tokens/s, Running: 82 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.9%, CPU KV cache usage: 0.0%
INFO 05-17 16:53:38 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.2 tokens/s, Running: 82 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.0%, CPU KV cache usage: 0.0%
INFO:     ::1:35174 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:53:43 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.0 tokens/s, Running: 80 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.0%, CPU KV cache usage: 0.0%
INFO:     ::1:35056 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:53:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.4 tokens/s, Running: 80 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:53:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.5 tokens/s, Running: 80 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.3%, CPU KV cache usage: 0.0%
INFO:     ::1:35042 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.8 tokens/s, Running: 79 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.5%, CPU KV cache usage: 0.0%
INFO:     ::1:35130 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.3 tokens/s, Running: 77 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.5%, CPU KV cache usage: 0.0%
INFO:     ::1:34997 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.7 tokens/s, Running: 77 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.8%, CPU KV cache usage: 0.0%
INFO:     ::1:35158 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:34972 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.2 tokens/s, Running: 75 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.7%, CPU KV cache usage: 0.0%
INFO 05-17 16:54:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.0 tokens/s, Running: 75 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:54:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.9 tokens/s, Running: 75 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.9%, CPU KV cache usage: 0.0%
INFO:     ::1:35064 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.8 tokens/s, Running: 74 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.0%, CPU KV cache usage: 0.0%
INFO:     ::1:35148 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:40 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.4 tokens/s, Running: 72 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.0%, CPU KV cache usage: 0.0%
INFO:     ::1:34954 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.0 tokens/s, Running: 71 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.1%, CPU KV cache usage: 0.0%
INFO:     ::1:34990 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35088 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.4 tokens/s, Running: 70 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.2%, CPU KV cache usage: 0.0%
INFO:     ::1:35082 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:54:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.1 tokens/s, Running: 68 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.2%, CPU KV cache usage: 0.0%
INFO:     ::1:35162 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:55:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.9 tokens/s, Running: 68 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.3%, CPU KV cache usage: 0.0%
INFO 05-17 16:55:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.8 tokens/s, Running: 68 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:55:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.8 tokens/s, Running: 68 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:55:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.8 tokens/s, Running: 68 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.5%, CPU KV cache usage: 0.0%
INFO 05-17 16:55:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.8 tokens/s, Running: 68 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.7%, CPU KV cache usage: 0.0%
INFO:     ::1:35110 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:34938 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:55:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.4 tokens/s, Running: 66 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.7%, CPU KV cache usage: 0.0%
INFO 05-17 16:55:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.2 tokens/s, Running: 66 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.9%, CPU KV cache usage: 0.0%
INFO 05-17 16:55:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.2 tokens/s, Running: 64 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.9%, CPU KV cache usage: 0.0%
INFO:     ::1:35086 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35044 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:34942 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:55:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.0 tokens/s, Running: 63 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.9%, CPU KV cache usage: 0.0%
INFO 05-17 16:55:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.7 tokens/s, Running: 63 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.0%, CPU KV cache usage: 0.0%
INFO:     ::1:35058 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:55:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.1 tokens/s, Running: 62 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.0%, CPU KV cache usage: 0.0%
INFO 05-17 16:56:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.9 tokens/s, Running: 62 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:56:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.0 tokens/s, Running: 61 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.3%, CPU KV cache usage: 0.0%
INFO:     ::1:35150 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35146 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35180 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:56:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 24.5 tokens/s, Running: 59 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.3%, CPU KV cache usage: 0.0%
INFO:     ::1:35098 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:34962 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:56:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.6 tokens/s, Running: 57 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:56:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.1 tokens/s, Running: 57 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.2%, CPU KV cache usage: 0.0%
INFO:     ::1:35188 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:56:38 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.0 tokens/s, Running: 56 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:56:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.2 tokens/s, Running: 56 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.4%, CPU KV cache usage: 0.0%
INFO 05-17 16:56:50 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.0 tokens/s, Running: 56 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.6%, CPU KV cache usage: 0.0%
INFO:     ::1:34988 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:56:58 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.7 tokens/s, Running: 55 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.7%, CPU KV cache usage: 0.0%
INFO 05-17 16:57:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.7 tokens/s, Running: 55 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.8%, CPU KV cache usage: 0.0%
INFO:     ::1:35068 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:34986 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35030 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:57:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.3 tokens/s, Running: 51 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.3%, CPU KV cache usage: 0.0%
INFO:     ::1:34944 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:34978 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:57:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.9 tokens/s, Running: 50 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.3%, CPU KV cache usage: 0.0%
INFO 05-17 16:57:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.5 tokens/s, Running: 50 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.5%, CPU KV cache usage: 0.0%
INFO 05-17 16:57:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.6 tokens/s, Running: 50 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.7%, CPU KV cache usage: 0.0%
INFO 05-17 16:57:38 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.6 tokens/s, Running: 49 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.7%, CPU KV cache usage: 0.0%
INFO:     ::1:34958 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:57:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.9 tokens/s, Running: 49 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:57:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.2 tokens/s, Running: 49 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.9%, CPU KV cache usage: 0.0%
INFO 05-17 16:57:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.5 tokens/s, Running: 49 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.0%, CPU KV cache usage: 0.0%
INFO:     ::1:35094 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:58:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.1 tokens/s, Running: 48 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.1%, CPU KV cache usage: 0.0%
INFO:     ::1:35054 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:58:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 30.3 tokens/s, Running: 47 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.1%, CPU KV cache usage: 0.0%
INFO 05-17 16:58:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.0 tokens/s, Running: 47 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.2%, CPU KV cache usage: 0.0%
INFO 05-17 16:58:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.0 tokens/s, Running: 47 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.3%, CPU KV cache usage: 0.0%
INFO 05-17 16:58:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.0 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.3%, CPU KV cache usage: 0.0%
INFO:     ::1:34928 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:58:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.1 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.5%, CPU KV cache usage: 0.0%
INFO 05-17 16:58:40 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 30.4 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.6%, CPU KV cache usage: 0.0%
INFO 05-17 16:58:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 24.1 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.7%, CPU KV cache usage: 0.0%
INFO:     ::1:35014 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:58:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.8 tokens/s, Running: 45 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.6%, CPU KV cache usage: 0.0%
INFO 05-17 16:58:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.4 tokens/s, Running: 45 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.8%, CPU KV cache usage: 0.0%
INFO:     ::1:35062 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:59:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.1 tokens/s, Running: 43 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.6%, CPU KV cache usage: 0.0%
INFO:     ::1:35000 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:59:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.7 tokens/s, Running: 43 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:59:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.4 tokens/s, Running: 43 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.9%, CPU KV cache usage: 0.0%
INFO 05-17 16:59:20 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.1 tokens/s, Running: 43 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.9%, CPU KV cache usage: 0.0%
INFO:     ::1:34926 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:59:26 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.2 tokens/s, Running: 41 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.6%, CPU KV cache usage: 0.0%
INFO:     ::1:35100 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:59:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.6 tokens/s, Running: 41 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.8%, CPU KV cache usage: 0.0%
INFO 05-17 16:59:37 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.6 tokens/s, Running: 41 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.9%, CPU KV cache usage: 0.0%
INFO:     ::1:35036 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35118 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:59:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.6 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.7%, CPU KV cache usage: 0.0%
INFO 05-17 16:59:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.7 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.8%, CPU KV cache usage: 0.0%
INFO:     ::1:35076 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:34992 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 16:59:56 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.0 tokens/s, Running: 37 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.5%, CPU KV cache usage: 0.0%
INFO 05-17 17:00:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.6 tokens/s, Running: 37 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.7%, CPU KV cache usage: 0.0%
INFO:     ::1:35066 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:00:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.3 tokens/s, Running: 36 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.7%, CPU KV cache usage: 0.0%
INFO 05-17 17:00:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.0 tokens/s, Running: 36 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.7%, CPU KV cache usage: 0.0%
INFO 05-17 17:00:20 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.2 tokens/s, Running: 36 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.8%, CPU KV cache usage: 0.0%
INFO:     ::1:35092 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:00:27 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.7 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.5%, CPU KV cache usage: 0.0%
INFO:     ::1:35154 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:00:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.0 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.7%, CPU KV cache usage: 0.0%
INFO:     ::1:34930 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35112 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:00:40 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 20.5 tokens/s, Running: 32 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.3%, CPU KV cache usage: 0.0%
INFO 05-17 17:00:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.9 tokens/s, Running: 32 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.4%, CPU KV cache usage: 0.0%
INFO 05-17 17:00:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.7 tokens/s, Running: 32 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 8.5%, CPU KV cache usage: 0.0%
INFO 05-17 17:00:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.9 tokens/s, Running: 30 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.9%, CPU KV cache usage: 0.0%
INFO:     ::1:35090 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35142 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35190 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:01:05 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.5 tokens/s, Running: 29 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.7%, CPU KV cache usage: 0.0%
INFO:     ::1:35122 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35070 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:01:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.4 tokens/s, Running: 27 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.2%, CPU KV cache usage: 0.0%
INFO 05-17 17:01:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.9 tokens/s, Running: 27 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.3%, CPU KV cache usage: 0.0%
INFO:     ::1:35060 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35116 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:01:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.5 tokens/s, Running: 25 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.9%, CPU KV cache usage: 0.0%
INFO:     ::1:35124 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35080 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:01:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.8 tokens/s, Running: 22 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.9%, CPU KV cache usage: 0.0%
INFO:     ::1:35096 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35164 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35152 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:01:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.7 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.4%, CPU KV cache usage: 0.0%
INFO 05-17 17:01:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.9 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.5%, CPU KV cache usage: 0.0%
INFO 05-17 17:01:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.7 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.6%, CPU KV cache usage: 0.0%
INFO:     ::1:34948 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:01:53 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.4 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.4%, CPU KV cache usage: 0.0%
INFO 05-17 17:01:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.2 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.4%, CPU KV cache usage: 0.0%
INFO 05-17 17:02:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.7 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.5%, CPU KV cache usage: 0.0%
INFO:     ::1:35002 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:02:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.5 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.3%, CPU KV cache usage: 0.0%
INFO 05-17 17:02:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.4 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.4%, CPU KV cache usage: 0.0%
INFO 05-17 17:02:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.5 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.4%, CPU KV cache usage: 0.0%
INFO 05-17 17:02:27 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.4 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.5%, CPU KV cache usage: 0.0%
INFO 05-17 17:02:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.4 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.6%, CPU KV cache usage: 0.0%
INFO 05-17 17:02:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.4 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.6%, CPU KV cache usage: 0.0%
INFO:     ::1:35018 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:02:45 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.6 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.4%, CPU KV cache usage: 0.0%
INFO:     ::1:34982 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:02:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.4 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%
INFO 05-17 17:02:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.3%, CPU KV cache usage: 0.0%
INFO:     ::1:35182 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:03:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.1 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.0%, CPU KV cache usage: 0.0%
INFO 05-17 17:03:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.6 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.1%, CPU KV cache usage: 0.0%
INFO:     ::1:34936 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35078 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:03:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.6 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.5%, CPU KV cache usage: 0.0%
INFO 05-17 17:03:19 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.1 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.5%, CPU KV cache usage: 0.0%
INFO:     ::1:35084 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35052 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:03:25 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.7 tokens/s, Running: 11 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO:     ::1:35104 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:03:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.7 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO 05-17 17:03:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.9 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-17 17:03:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.9 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-17 17:03:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.6 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO:     ::1:35184 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:03:53 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.2 tokens/s, Running: 9 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.5%, CPU KV cache usage: 0.0%
INFO 05-17 17:03:58 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.8 tokens/s, Running: 9 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.5%, CPU KV cache usage: 0.0%
INFO:     ::1:35050 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:04:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.8 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO:     ::1:35144 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:04:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.2 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.8%, CPU KV cache usage: 0.0%
INFO 05-17 17:04:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.6 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
INFO 05-17 17:04:20 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.6 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.0%, CPU KV cache usage: 0.0%
INFO:     ::1:35192 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:35039 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:04:25 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.5 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.2%, CPU KV cache usage: 0.0%
INFO:     ::1:35186 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:04:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.6 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
INFO:     ::1:35008 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:04:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.7 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
INFO:     ::1:35156 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:04:40 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.7 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO:     ::1:35168 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 17:04:45 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 17:04:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO:     ::1:34974 - "POST /v1/completions HTTP/1.1" 200 OK
Results written to .artifact/benchmarks/results/85153809-bf50-4540-8d95-680a459b3d21.jsonl
Killing process 32669...
/var/spool/slurmd/job3676860/slurm_script: line 45: 32636 Killed                  apptainer run --nv --home /mnt/petrelfs/huqinghao/xzyao/:/home/xiayao --bind /mnt/petrelfs/huqinghao/xzyao/code/vllm:/vllm --bind /mnt/petrelfs/huqinghao/xzyao/code/triteia:/triteia --env PYTHONPATH=/vllm:/triteia --env CUDA_LAUNCH_BLOCKING=1 --env TVM_TARGET=nvidia/nvidia-a100 --env TRANSFORMERS_OFFLINE=1 --env NUMEXPR_MAX_THREADS=128 --env USE_BITBLAS=1 --env BITBLAS_TARGET=nvidia/nvidia-a100 --env RAY_DEDUP_LOGS=0 --workdir /vllm /mnt/petrelfs/huqinghao/xzyao/images/vllm-0.4.1.sif python3 /vllm/vllm/entrypoints/openai/api_server.py --model /vllm/.idea/full_models/Llama-2-13b-hf --enable-delta --disable-log-requests --gpu-memory-utilization 0.85 --delta-modules delta-1=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1 delta-2=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2 delta-3=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3 delta-4=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4 delta-5=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5 delta-6=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6 delta-7=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7 delta-8=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8 delta-9=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-9 delta-10=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-10 delta-11=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-11 delta-12=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-12 delta-13=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-13 delta-14=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-14 delta-15=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-15 delta-16=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-16 delta-17=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-17 delta-18=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-18 delta-19=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-19 delta-20=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-20 delta-21=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-21 delta-22=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-22 delta-23=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-23 delta-24=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-24 delta-25=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-25 delta-26=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-26 delta-27=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-27 delta-28=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-28 delta-29=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-29 delta-30=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-30 delta-31=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-31 delta-32=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-32 --max-deltas 24 --max-cpu-deltas 32 --tensor-parallel-size 4 --enforce-eager
