/mnt/hwfile/huqinghao/miniconda3/bin/python
2024-05-17 17:40:11,257 - INFO - Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2024-05-17 17:40:11,258 - INFO - Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-05-17 17:40:11,258 - INFO - NumExpr defaulting to 8 threads.
2024-05-17 17:40:12,382	INFO scripts.py:1182 -- Did not find any active Ray processes.

==========
== CUDA ==
==========

CUDA Version 12.1.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a706d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71450>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 05-17 17:40:26 api_server.py:191] vLLM API server version 0.3.3
INFO 05-17 17:40:26 api_server.py:192] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, lora_modules=[], delta_modules=[Delta(name='delta-1', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1'), Delta(name='delta-2', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2'), Delta(name='delta-3', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3'), Delta(name='delta-4', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4'), Delta(name='delta-5', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5'), Delta(name='delta-6', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6'), Delta(name='delta-7', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7'), Delta(name='delta-8', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8'), Delta(name='delta-9', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-9'), Delta(name='delta-10', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-10'), Delta(name='delta-11', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-11'), Delta(name='delta-12', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-12'), Delta(name='delta-13', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-13'), Delta(name='delta-14', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-14'), Delta(name='delta-15', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-15'), Delta(name='delta-16', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-16'), Delta(name='delta-17', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-17'), Delta(name='delta-18', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-18'), Delta(name='delta-19', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-19'), Delta(name='delta-20', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-20'), Delta(name='delta-21', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-21'), Delta(name='delta-22', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-22'), Delta(name='delta-23', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-23'), Delta(name='delta-24', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-24'), Delta(name='delta-25', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-25'), Delta(name='delta-26', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-26'), Delta(name='delta-27', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-27'), Delta(name='delta-28', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-28'), Delta(name='delta-29', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-29'), Delta(name='delta-30', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-30'), Delta(name='delta-31', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-31'), Delta(name='delta-32', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-32')], swap_modules=[], chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, seed=0, swap_space=4, gpu_memory_utilization=0.85, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=True, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=64, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=32, enable_delta=True, max_deltas=24, max_cpu_deltas=32, max_delta_bitwidth=4, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_prefetch=False, scheduler_policy='fcfs', max_swap_slots=1, max_cpu_models=4, enable_swap=False, engine_use_ray=False, disable_log_requests=True, max_log_len=None)
2024-05-17 17:40:29,942	INFO worker.py:1749 -- Started a local Ray instance.
INFO 05-17 17:40:31 llm_engine.py:90] Initializing an LLM engine (v0.3.3) with config: model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, lora_config=None, delta_config=DeltaConfig(max_deltas=24, max_bitwidth=4, delta_dtype=torch.int8, max_cpu_deltas=32, delta_extra_vocab_size=0, pack_factor=Fraction(2, 1), kernel=<QuantKernel.TRITON: 'triton'>), swap_config=None, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, seed=0)
INFO 05-17 17:40:31 llm_engine.py:243] ignored verifying delta_config
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71d20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71150>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a725f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a729e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72110>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a703d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71390>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863c0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a713f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72140>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72800>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71f30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863c370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71510>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception ignored in: <function TempDirectory.__del__ at 0x7f83236d7eb0>
Traceback (most recent call last):
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
    self.remove()
  File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
    if self.temp_dir:
AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a701f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72350>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a737f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a726e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71030>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71000>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72650>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72980>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863c070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71030>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a4bb20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71540>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71c00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71ff0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863c9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a702b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71270>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73d30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863c400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71150>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a704f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863c040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70160>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71420>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71a20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863cbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71810>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a714b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70220>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a725c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863d270>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72530>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71120>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71c30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863c700>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71540>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71a20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71420>: Failed to establish a new connection: [Errno 111] Connection refused'))
Using bitblas
BitBLAS Operator not loaded, retrying in 5 seconds...
Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/01283121bc1207ccb70512cd16a8297b2694ac7656e4fb007240ea11ed77401f/tvm_rt_mod'
WARNING 05-17 17:53:53 models.py:48] Using bitblas delta modules
INFO 05-17 17:53:54 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=96239)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7face650e200>
[36m(RayWorkerVllm pid=96239)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=96239)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=96239)[0m     self.remove()
[36m(RayWorkerVllm pid=96239)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=96239)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=96239)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=96402)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7fba87d7a200>
[36m(RayWorkerVllm pid=96402)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=96402)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=96402)[0m     self.remove()
[36m(RayWorkerVllm pid=96402)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=96402)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=96402)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70490>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=96239)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7face650e200>
[36m(RayWorkerVllm pid=96239)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=96239)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=96239)[0m     self.remove()
[36m(RayWorkerVllm pid=96239)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=96239)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=96239)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863ca60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a721a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72440>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a715d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863d4e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71660>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a711e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72410>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a721d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863db70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72500>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a710f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72830>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72230>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71e40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72770>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72380>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863d4b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73970>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a717b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a706a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a4bd60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a729e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71b40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71210>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a703a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863d840>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a739a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71600>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71660>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72b00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863d960>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a729e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a712a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a739d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863d000>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=96402)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7fba87d7a200>
[36m(RayWorkerVllm pid=96402)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=96402)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=96402)[0m     self.remove()
[36m(RayWorkerVllm pid=96402)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=96402)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=96402)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71300>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a716f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a729b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863d6f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72800>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a712a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a711b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863c2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71300>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a716f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a729b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863c5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a712a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863e470>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a728f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72a70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863ddb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71c00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a720e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863c100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71840>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72110>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a704f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72170>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72a40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a723e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a70df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863dfc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a73f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a71840>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72110>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a704f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a4bd60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72350>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72500>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a72140>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a718a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a711e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=96569)[0m Using bitblas
[36m(RayWorkerVllm pid=96239)[0m Using bitblas
[36m(RayWorkerVllm pid=96402)[0m Using bitblas
[36m(RayWorkerVllm pid=96239)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=96239)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=96402)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=96402)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=96239)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=96239)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=96402)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=96402)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/1d390a6c287a95d7deaeb54d9e3aaa6ac93890093ab49cec2cadbc9000015794/tvm_rt_mod'
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:02:39 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:02:39 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:02:53 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:02:53 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:10:28 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:10:28 selector.py:16] Using FlashAttention backend.
INFO 05-17 18:10:40 model_runner.py:161] Loading model weights took 6.1114 GB
INFO 05-17 18:10:40 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:10:42 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:10:42 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:10:42 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:10:42 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:10:42 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:10:42 worker_manager.py:297] Starting prefetching thread
WARNING 05-17 18:10:44 quant_linear_triton.py:557] We should warm up the kernel here 
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f863ca60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f8a716f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:10:45 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:10:46 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:10:46 quant_linear_triton.py:557] We should warm up the kernel here 
INFO 05-17 18:10:58 ray_gpu_executor.py:275] # GPU blocks: 6431, # CPU blocks: 1310
INFO 05-17 18:11:01 scheduler.py:136] Using fcfs policy.
INFO 05-17 18:11:01 block_manager.py:264] disable automatic prefix caching
WARNING 05-17 18:11:01 serving_chat.py:373] No chat template provided. Chat API will not work.
INFO:     Started server process [87889]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     ::1:60706 - "GET /sysinfo HTTP/1.1" 200 OK
Translating from base-model to /vllm/.idea/full_models/Llama-2-13b-hf
Warming up starts
{'id': 26, 'prompt': 'USER: Write me a function to lazily compute a Fibonacci sequence in Clojure. \nASSISTANT:', 'timestamp': 0, 'model': 'delta-2', 'min_tokens': 419, 'max_tokens': 419}
Prefetching is disabled
WARNING 05-17 18:11:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
INFO 05-17 18:11:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:11:04 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:11:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:11:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:11:04 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:11:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:11:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:11:04 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:11:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:11:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:11:04 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:11:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:11:17 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.060 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:11:18 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:11:18 worker_manager.py:379] [1715940678.027487] activating delta
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:11:18 worker_manager.py:384] [1715940678.183359] CPU -> GPU time: 0.1558
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:11:19 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.823 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:11:19 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:11:19 worker_manager.py:379] [1715940679.769316] activating delta
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:11:19 worker_manager.py:384] [1715940679.9024417] CPU -> GPU time: 0.1331
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:11:21 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.866 seconds
INFO 05-17 18:11:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:11:21 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:11:21 worker_manager.py:379] [1715940681.812188] activating delta
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:11:21 worker_manager.py:384] [1715940681.9450932] CPU -> GPU time: 0.1328
INFO 05-17 18:11:22 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.904 seconds
INFO 05-17 18:11:22 worker_manager.py:364] Main thread loading delta 2 done
INFO 05-17 18:11:22 worker_manager.py:379] [1715940682.845454] activating delta
INFO 05-17 18:11:22 worker_manager.py:384] [1715940682.9467432] CPU -> GPU time: 0.1012
INFO 05-17 18:11:26 metrics.py:276] Avg prompt throughput: 5.7 tokens/s, Avg generation throughput: 2.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 18:11:32 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 18:11:37 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 18:11:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 18:11:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 18:11:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:11:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:12:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:12:08 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:12:13 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:12:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:12:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-17 18:12:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-17 18:12:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-17 18:12:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-17 18:12:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 18:12:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 18:12:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 18:12:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 18:13:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO:     ::1:60708 - "POST /v1/completions HTTP/1.1" 200 OK
Warming up ends
Issuing queries
sending 1 queries at 0.4
sending 1 queries at 1.1
sending 1 queries at 1.5
sending 1 queries at 1.9000000000000001
sending 1 queries at 2.2
sending 1 queries at 2.7
sending 1 queries at 3.0
sending 1 queries at 4.1000000000000005
sending 1 queries at 5.800000000000001
sending 1 queries at 6.0
sending 1 queries at 6.800000000000001
sending 1 queries at 7.2
sending 1 queries at 7.6000000000000005
sending 2 queries at 8.9
sending 2 queries at 9.0
sending 1 queries at 9.9
sending 1 queries at 10.600000000000001
sending 1 queries at 11.700000000000001
sending 1 queries at 13.600000000000001
sending 1 queries at 14.4
sending 1 queries at 14.700000000000001
sending 2 queries at 15.5
sending 1 queries at 16.0
sending 1 queries at 16.1
sending 1 queries at 17.6
sending 1 queries at 17.900000000000002
sending 1 queries at 18.2
sending 1 queries at 18.3
sending 1 queries at 19.1
sending 1 queries at 19.400000000000002
sending 2 queries at 19.8
sending 1 queries at 20.3
sending 1 queries at 20.8
sending 1 queries at 21.3
sending 1 queries at 22.700000000000003
sending 1 queries at 23.3
sending 1 queries at 23.5
sending 1 queries at 23.8
sending 2 queries at 24.400000000000002
sending 1 queries at 25.0
sending 1 queries at 25.5
sending 1 queries at 25.6
sending 1 queries at 25.700000000000003
sending 1 queries at 25.900000000000002
sending 1 queries at 26.1
sending 1 queries at 26.5
sending 1 queries at 26.8
sending 2 queries at 29.1
sending 1 queries at 29.200000000000003
sending 1 queries at 29.3
sending 1 queries at 29.8
sending 1 queries at 30.0
Prefetching is disabled
WARNING 05-17 18:13:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
INFO 05-17 18:13:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:13:06 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:13:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:13:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:13:06 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:13:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:13:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:13:06 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:13:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 13 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:13:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:13:06 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 18:13:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:13:20 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.456 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:13:20 worker_manager.py:364] Main thread loading delta 13 done
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 18:13:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:13:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.719 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:13:23 worker_manager.py:364] Main thread loading delta 13 done
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:13:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.099 seconds
Prefetching is disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:13:23 worker_manager.py:364] Main thread loading delta 13 done
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 18:13:25 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 19.337 seconds
INFO 05-17 18:13:26 worker_manager.py:364] Main thread loading delta 13 done
Prefetching is disabled
Prefetching is disabled
WARNING 05-17 18:13:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:13:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:13:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:13:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
INFO 05-17 18:13:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:13:26 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:13:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:13:26 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:13:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:13:26 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:13:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:13:26 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
INFO 05-17 18:13:31 metrics.py:276] Avg prompt throughput: 2.1 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
total threads: 58
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:13:35 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 9.308 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:13:35 worker_manager.py:364] Main thread loading delta 1 done
Prefetching is disabled
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:13:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:13:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:13:36 models.py:263] [main] Lossless Compression Disabled
Prefetching is disabled
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:13:39 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.718 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:13:39 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:13:39 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:13:39 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:13:39 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:13:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:13:45 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 19.129 seconds
INFO 05-17 18:13:45 worker_manager.py:364] Main thread loading delta 1 done
WARNING 05-17 18:13:45 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
INFO 05-17 18:13:45 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:13:45 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:13:47 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 20.747 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:13:47 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:13:47 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:13:47 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:13:47 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:13:49 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.337 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:13:49 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:13:49 worker_manager.py:344] Missed prefetch, fall back to loading delta 8 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:13:49 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:13:49 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:13:51 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.254 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:13:51 worker_manager.py:364] Main thread loading delta 3 done
INFO 05-17 18:13:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:13:51 worker_manager.py:344] Missed prefetch, fall back to loading delta 8 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:13:51 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:13:51 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:14:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:02 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.670 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:02 worker_manager.py:364] Main thread loading delta 8 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:14:02 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:02 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:02 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:03 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.516 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:03 worker_manager.py:364] Main thread loading delta 8 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:14:03 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:03 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:03 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:14:04 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.234 seconds
INFO 05-17 18:14:04 worker_manager.py:364] Main thread loading delta 3 done
WARNING 05-17 18:14:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 8 now
INFO 05-17 18:14:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:14:04 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:05 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.573 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:05 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:14:05 worker_manager.py:344] Missed prefetch, fall back to loading delta 8 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:05 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:05 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:14:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:15 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.101 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:15 worker_manager.py:364] Main thread loading delta 9 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:14:16 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:16 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:16 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:17 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.546 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:18 worker_manager.py:364] Main thread loading delta 9 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:14:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:18 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:21 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.392 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:21 worker_manager.py:364] Main thread loading delta 8 done
INFO 05-17 18:14:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:14:21 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:21 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:21 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:14:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.894 seconds
INFO 05-17 18:14:23 worker_manager.py:364] Main thread loading delta 8 done
WARNING 05-17 18:14:23 worker_manager.py:344] Missed prefetch, fall back to loading delta 9 now
INFO 05-17 18:14:23 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:14:23 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:29 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.080 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:29 worker_manager.py:364] Main thread loading delta 10 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:14:29 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:29 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:29 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:30 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.827 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:31 worker_manager.py:364] Main thread loading delta 10 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:14:31 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:31 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:31 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:14:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:35 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.699 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:35 worker_manager.py:364] Main thread loading delta 9 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:14:35 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:35 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:35 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:14:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.767 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:42 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:14:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:42 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:14:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 19.586 seconds
INFO 05-17 18:14:42 worker_manager.py:364] Main thread loading delta 9 done
WARNING 05-17 18:14:43 worker_manager.py:344] Missed prefetch, fall back to loading delta 10 now
INFO 05-17 18:14:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:14:43 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:44 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.364 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:44 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:14:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:44 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:14:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:53 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.778 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:53 worker_manager.py:364] Main thread loading delta 10 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:14:53 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:53 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:14:53 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:55 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.749 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:55 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:14:55 worker_manager.py:344] Missed prefetch, fall back to loading delta 16 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:55 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:14:55 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:58 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.317 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:58 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:14:58 worker_manager.py:344] Missed prefetch, fall back to loading delta 16 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:58 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:14:58 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:14:59 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.434 seconds
INFO 05-17 18:14:59 worker_manager.py:364] Main thread loading delta 10 done
WARNING 05-17 18:14:59 worker_manager.py:344] Missed prefetch, fall back to loading delta 11 now
INFO 05-17 18:14:59 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:14:59 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:15:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:05 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.219 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:06 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:15:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:06 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:10 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.599 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:10 worker_manager.py:364] Main thread loading delta 16 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:15:10 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:10 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:10 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:15:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:15:15 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.551 seconds
INFO 05-17 18:15:15 worker_manager.py:364] Main thread loading delta 11 done
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:15:15 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.377 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:15:15 worker_manager.py:364] Main thread loading delta 16 done
WARNING 05-17 18:15:15 worker_manager.py:344] Missed prefetch, fall back to loading delta 14 now
INFO 05-17 18:15:15 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:15:15 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:15:15 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:15:15 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:15:15 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:18 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.480 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:18 worker_manager.py:364] Main thread loading delta 17 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:15:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:18 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:20 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.375 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:20 worker_manager.py:364] Main thread loading delta 14 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:15:20 worker_manager.py:344] Missed prefetch, fall back to loading delta 16 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:20 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:20 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:15:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:15:22 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.132 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:15:22 worker_manager.py:364] Main thread loading delta 17 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:15:22 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:15:22 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:15:22 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:15:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:15:32 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.436 seconds
INFO 05-17 18:15:32 worker_manager.py:364] Main thread loading delta 14 done
WARNING 05-17 18:15:33 worker_manager.py:344] Missed prefetch, fall back to loading delta 16 now
INFO 05-17 18:15:33 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:15:33 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:33 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.163 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:33 worker_manager.py:364] Main thread loading delta 16 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:15:34 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:34 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:34 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:36 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.165 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:36 worker_manager.py:364] Main thread loading delta 18 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:15:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 19 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:36 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:15:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 8.285 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:42 worker_manager.py:364] Main thread loading delta 17 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:15:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:42 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:15:43 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 20.802 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:15:43 worker_manager.py:364] Main thread loading delta 18 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:15:43 worker_manager.py:344] Missed prefetch, fall back to loading delta 19 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:15:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:15:43 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:48 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.556 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:48 worker_manager.py:364] Main thread loading delta 19 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:15:48 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:48 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:15:48 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:15:50 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.757 seconds
INFO 05-17 18:15:50 worker_manager.py:364] Main thread loading delta 16 done
WARNING 05-17 18:15:51 worker_manager.py:344] Missed prefetch, fall back to loading delta 17 now
INFO 05-17 18:15:51 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:15:51 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:15:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:54 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.634 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:54 worker_manager.py:364] Main thread loading delta 18 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:15:54 worker_manager.py:344] Missed prefetch, fall back to loading delta 19 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:54 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:15:54 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:00 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.234 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:00 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:16:00 worker_manager.py:344] Missed prefetch, fall back to loading delta 21 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:00 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:00 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:01 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.230 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:01 worker_manager.py:364] Main thread loading delta 19 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:16:01 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:01 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:01 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:16:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:05 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.093 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:05 worker_manager.py:364] Main thread loading delta 19 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:16:05 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:05 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:05 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:16:07 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.730 seconds
INFO 05-17 18:16:07 worker_manager.py:364] Main thread loading delta 17 done
WARNING 05-17 18:16:07 worker_manager.py:344] Missed prefetch, fall back to loading delta 18 now
INFO 05-17 18:16:07 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:16:07 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:16:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:12 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.053 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:12 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:16:12 worker_manager.py:344] Missed prefetch, fall back to loading delta 21 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:12 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:12 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:16 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.783 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:16 worker_manager.py:364] Main thread loading delta 21 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:16:16 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:16 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:16 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:21 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.671 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:21 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:16:21 worker_manager.py:344] Missed prefetch, fall back to loading delta 21 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:21 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:21 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:16:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.294 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:23 worker_manager.py:364] Main thread loading delta 21 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:16:24 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:24 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:24 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:16:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 20.146 seconds
INFO 05-17 18:16:28 worker_manager.py:364] Main thread loading delta 18 done
WARNING 05-17 18:16:28 worker_manager.py:344] Missed prefetch, fall back to loading delta 19 now
INFO 05-17 18:16:28 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:16:28 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:28 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.964 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:28 worker_manager.py:364] Main thread loading delta 22 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:16:29 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:29 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:29 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:16:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:38 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.275 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:38 worker_manager.py:364] Main thread loading delta 22 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:16:38 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:38 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:38 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:39 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.341 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:39 worker_manager.py:364] Main thread loading delta 21 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:16:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:40 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.421 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:40 worker_manager.py:364] Main thread loading delta 23 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:16:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 24 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:16:40 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:16:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:16:48 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 20.234 seconds
INFO 05-17 18:16:48 worker_manager.py:364] Main thread loading delta 19 done
WARNING 05-17 18:16:48 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
INFO 05-17 18:16:48 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:16:48 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:50 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.053 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:50 worker_manager.py:364] Main thread loading delta 23 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:16:50 worker_manager.py:344] Missed prefetch, fall back to loading delta 24 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:50 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:16:50 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:16:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:53 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.302 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:53 worker_manager.py:364] Main thread loading delta 22 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:16:53 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:53 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:16:53 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:00 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 20.059 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:00 worker_manager.py:364] Main thread loading delta 24 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:17:01 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:01 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:01 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:17:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:04 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.380 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:04 worker_manager.py:364] Main thread loading delta 24 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:17:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:04 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:17:07 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 19.130 seconds
INFO 05-17 18:17:07 worker_manager.py:364] Main thread loading delta 20 done
WARNING 05-17 18:17:08 worker_manager.py:344] Missed prefetch, fall back to loading delta 21 now
INFO 05-17 18:17:08 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:17:08 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:08 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.418 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:08 worker_manager.py:364] Main thread loading delta 23 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:17:08 worker_manager.py:344] Missed prefetch, fall back to loading delta 24 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:08 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:08 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:17:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:18 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.656 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:18 worker_manager.py:364] Main thread loading delta 26 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:17:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 27 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:18 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:19 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.093 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:19 worker_manager.py:364] Main thread loading delta 26 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:17:19 worker_manager.py:344] Missed prefetch, fall back to loading delta 27 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:19 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:19 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:17:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:22 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.879 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:22 worker_manager.py:364] Main thread loading delta 24 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:17:22 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:22 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:22 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:17:25 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.607 seconds
INFO 05-17 18:17:25 worker_manager.py:364] Main thread loading delta 21 done
WARNING 05-17 18:17:25 worker_manager.py:344] Missed prefetch, fall back to loading delta 22 now
INFO 05-17 18:17:25 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:17:25 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:17:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:33 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.914 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:33 worker_manager.py:364] Main thread loading delta 27 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:17:33 worker_manager.py:344] Missed prefetch, fall back to loading delta 30 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:33 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:33 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:33 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.472 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:33 worker_manager.py:364] Main thread loading delta 26 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:17:34 worker_manager.py:344] Missed prefetch, fall back to loading delta 27 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:34 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:34 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:35 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.288 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:35 worker_manager.py:364] Main thread loading delta 27 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:17:36 worker_manager.py:344] Missed prefetch, fall back to loading delta 30 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:36 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:36 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:17:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:17:51 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 25.950 seconds
INFO 05-17 18:17:51 worker_manager.py:364] Main thread loading delta 22 done
INFO 05-17 18:17:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
WARNING 05-17 18:17:52 worker_manager.py:344] Missed prefetch, fall back to loading delta 23 now
INFO 05-17 18:17:52 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:17:52 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:52 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 19.256 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:52 worker_manager.py:364] Main thread loading delta 30 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:17:53 worker_manager.py:344] Missed prefetch, fall back to loading delta 31 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:53 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:17:53 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:54 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 18.073 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:54 worker_manager.py:364] Main thread loading delta 30 done
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:17:54 worker_manager.py:344] Missed prefetch, fall back to loading delta 31 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:54 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:17:54 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:54 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 20.877 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:55 worker_manager.py:364] Main thread loading delta 27 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:17:55 worker_manager.py:344] Missed prefetch, fall back to loading delta 30 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:55 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:17:55 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:18:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:18:06 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.941 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:18:06 worker_manager.py:364] Main thread loading delta 31 done
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:18:06 worker_manager.py:344] Missed prefetch, fall back to loading delta 32 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:18:06 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:18:06 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:18:08 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.585 seconds
INFO 05-17 18:18:08 worker_manager.py:364] Main thread loading delta 23 done
WARNING 05-17 18:18:08 worker_manager.py:344] Missed prefetch, fall back to loading delta 24 now
INFO 05-17 18:18:08 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:18:08 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:18:09 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.324 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:18:09 worker_manager.py:364] Main thread loading delta 30 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:18:09 worker_manager.py:344] Missed prefetch, fall back to loading delta 31 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:18:09 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:18:09 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:18:11 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.506 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:18:11 worker_manager.py:364] Main thread loading delta 31 done
INFO 05-17 18:18:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:18:12 worker_manager.py:344] Missed prefetch, fall back to loading delta 32 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:18:12 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:18:12 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:18:16 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.136 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:18:16 worker_manager.py:364] Main thread loading delta 32 done
INFO 05-17 18:18:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:18:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.094 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:18:23 worker_manager.py:364] Main thread loading delta 31 done
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:18:24 worker_manager.py:344] Missed prefetch, fall back to loading delta 32 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:18:24 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:18:24 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:18:26 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 17.413 seconds
INFO 05-17 18:18:26 worker_manager.py:364] Main thread loading delta 24 done
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:18:26 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.228 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:18:26 worker_manager.py:364] Main thread loading delta 32 done
WARNING 05-17 18:18:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 26 now
INFO 05-17 18:18:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:18:26 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:18:30 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 6.634 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:18:30 worker_manager.py:364] Main thread loading delta 32 done
INFO 05-17 18:18:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:18:34 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.620 seconds
INFO 05-17 18:18:34 worker_manager.py:364] Main thread loading delta 26 done
WARNING 05-17 18:18:34 worker_manager.py:344] Missed prefetch, fall back to loading delta 27 now
INFO 05-17 18:18:34 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:18:34 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:18:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:18:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.835 seconds
INFO 05-17 18:18:42 worker_manager.py:364] Main thread loading delta 27 done
WARNING 05-17 18:18:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 30 now
INFO 05-17 18:18:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:18:42 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:18:49 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.017 seconds
INFO 05-17 18:18:49 worker_manager.py:364] Main thread loading delta 30 done
WARNING 05-17 18:18:49 worker_manager.py:344] Missed prefetch, fall back to loading delta 31 now
INFO 05-17 18:18:49 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:18:49 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:18:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:18:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.593 seconds
INFO 05-17 18:18:57 worker_manager.py:364] Main thread loading delta 31 done
WARNING 05-17 18:18:57 worker_manager.py:344] Missed prefetch, fall back to loading delta 32 now
INFO 05-17 18:18:57 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:18:57 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:19:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:19:04 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.157 seconds
INFO 05-17 18:19:04 worker_manager.py:364] Main thread loading delta 32 done
INFO 05-17 18:19:10 metrics.py:276] Avg prompt throughput: 111.8 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO:     ::1:32838 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:19:16 metrics.py:276] Avg prompt throughput: 92.6 tokens/s, Avg generation throughput: 11.0 tokens/s, Running: 51 reqs, Swapped: 0 reqs, Pending: 5 reqs, GPU KV cache usage: 1.9%, CPU KV cache usage: 0.0%
INFO:     ::1:32888 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:19:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.5 tokens/s, Running: 51 reqs, Swapped: 0 reqs, Pending: 5 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
INFO:     ::1:32824 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:32880 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-17 18:19:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
INFO 05-17 18:19:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:19:26 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:19:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:19:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:19:26 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:19:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:19:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:19:26 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:19:26 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:19:26 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:19:26 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:19:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.2 tokens/s, Running: 50 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:19:39 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.290 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:19:39 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:19:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.639 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:19:41 worker_manager.py:364] Main thread loading delta 4 done
INFO 05-17 18:19:41 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.660 seconds
INFO 05-17 18:19:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 50 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
INFO 05-17 18:19:42 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:19:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.742 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:19:42 worker_manager.py:364] Main thread loading delta 4 done
INFO:     ::1:32904 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:32899 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:32901 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-17 18:19:45 worker_manager.py:344] Missed prefetch, fall back to loading delta 29 now
INFO 05-17 18:19:45 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:19:45 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:19:45 worker_manager.py:344] Missed prefetch, fall back to loading delta 29 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:19:45 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:19:45 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:19:45 worker_manager.py:344] Missed prefetch, fall back to loading delta 29 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:19:45 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:19:45 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:19:45 worker_manager.py:344] Missed prefetch, fall back to loading delta 29 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:19:45 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:19:45 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:19:52 metrics.py:276] Avg prompt throughput: 1.9 tokens/s, Avg generation throughput: 5.1 tokens/s, Running: 48 reqs, Swapped: 0 reqs, Pending: 3 reqs, GPU KV cache usage: 1.9%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:19:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.713 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:19:57 worker_manager.py:364] Main thread loading delta 29 done
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:19:58 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.611 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:19:58 worker_manager.py:364] Main thread loading delta 29 done
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:20:00 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.118 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:20:00 worker_manager.py:364] Main thread loading delta 29 done
INFO 05-17 18:20:01 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.958 seconds
INFO 05-17 18:20:01 worker_manager.py:364] Main thread loading delta 29 done
INFO 05-17 18:20:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 48 reqs, Swapped: 0 reqs, Pending: 3 reqs, GPU KV cache usage: 1.9%, CPU KV cache usage: 0.0%
INFO:     ::1:32892 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:20:08 metrics.py:276] Avg prompt throughput: 2.8 tokens/s, Avg generation throughput: 14.7 tokens/s, Running: 47 reqs, Swapped: 0 reqs, Pending: 3 reqs, GPU KV cache usage: 1.9%, CPU KV cache usage: 0.0%
INFO:     ::1:32918 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:20:15 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.4 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 3 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
INFO:     ::1:32902 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-17 18:20:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 25 now
INFO 05-17 18:20:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:20:18 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:20:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 25 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:20:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:20:18 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:20:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 25 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:20:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:20:18 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:20:18 worker_manager.py:344] Missed prefetch, fall back to loading delta 25 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:20:18 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:20:18 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:20:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.5 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 2 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
INFO 05-17 18:20:32 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 2 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:20:32 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.627 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:20:33 worker_manager.py:364] Main thread loading delta 25 done
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:20:34 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.964 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:20:34 worker_manager.py:364] Main thread loading delta 25 done
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:20:34 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.353 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:20:34 worker_manager.py:364] Main thread loading delta 25 done
INFO 05-17 18:20:37 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 19.265 seconds
INFO 05-17 18:20:37 worker_manager.py:364] Main thread loading delta 25 done
INFO 05-17 18:20:38 metrics.py:276] Avg prompt throughput: 3.2 tokens/s, Avg generation throughput: 0.2 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 2 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
INFO:     ::1:32818 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-17 18:20:41 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
INFO 05-17 18:20:41 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:20:41 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:20:41 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:20:41 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:20:41 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:20:41 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:20:41 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:20:41 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:20:41 worker_manager.py:344] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:20:41 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:20:41 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:20:51 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.656 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:20:51 worker_manager.py:364] Main thread loading delta 6 done
INFO 05-17 18:20:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.3 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.1%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:20:53 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.134 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:20:53 worker_manager.py:364] Main thread loading delta 6 done
INFO 05-17 18:20:56 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.571 seconds
INFO 05-17 18:20:56 worker_manager.py:364] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:20:56 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.580 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:20:56 worker_manager.py:364] Main thread loading delta 6 done
INFO 05-17 18:20:57 metrics.py:276] Avg prompt throughput: 4.0 tokens/s, Avg generation throughput: 0.2 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.1%, CPU KV cache usage: 0.0%
INFO 05-17 18:21:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.5 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:21:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.4 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.3%, CPU KV cache usage: 0.0%
INFO 05-17 18:21:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.4 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.4%, CPU KV cache usage: 0.0%
INFO 05-17 18:21:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.2 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.4%, CPU KV cache usage: 0.0%
INFO 05-17 18:21:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.0 tokens/s, Running: 46 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.5%, CPU KV cache usage: 0.0%
INFO 05-17 18:21:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.2 tokens/s, Running: 45 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.5%, CPU KV cache usage: 0.0%
INFO:     ::1:32934 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:21:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.2 tokens/s, Running: 45 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.6%, CPU KV cache usage: 0.0%
INFO 05-17 18:21:48 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 20.2 tokens/s, Running: 45 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.7%, CPU KV cache usage: 0.0%
INFO 05-17 18:21:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.0 tokens/s, Running: 45 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
INFO 05-17 18:22:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.1 tokens/s, Running: 44 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
INFO:     ::1:32874 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:32922 - "POST /v1/completions HTTP/1.1" 200 OK
WARNING 05-17 18:22:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
INFO 05-17 18:22:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 18:22:04 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96239)[0m WARNING 05-17 18:22:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:22:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:22:04 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96402)[0m WARNING 05-17 18:22:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:22:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:22:04 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=96569)[0m WARNING 05-17 18:22:04 worker_manager.py:344] Missed prefetch, fall back to loading delta 7 now
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:22:04 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:22:04 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 18:22:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.2 tokens/s, Running: 44 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:22:17 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.678 seconds
[36m(RayWorkerVllm pid=96569)[0m INFO 05-17 18:22:17 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:22:19 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 14.608 seconds
[36m(RayWorkerVllm pid=96402)[0m INFO 05-17 18:22:19 worker_manager.py:364] Main thread loading delta 7 done
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:22:21 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.457 seconds
[36m(RayWorkerVllm pid=96239)[0m INFO 05-17 18:22:21 worker_manager.py:364] Main thread loading delta 7 done
INFO 05-17 18:22:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 44 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
INFO 05-17 18:22:23 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 19.008 seconds
INFO 05-17 18:22:23 worker_manager.py:364] Main thread loading delta 7 done
INFO 05-17 18:22:27 metrics.py:276] Avg prompt throughput: 3.7 tokens/s, Avg generation throughput: 8.4 tokens/s, Running: 44 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
INFO:     ::1:32834 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:22:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.7 tokens/s, Running: 43 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
INFO 05-17 18:22:40 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.8 tokens/s, Running: 43 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.0%, CPU KV cache usage: 0.0%
INFO 05-17 18:22:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.8 tokens/s, Running: 43 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.0%, CPU KV cache usage: 0.0%
INFO:     ::1:32944 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:22:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.3 tokens/s, Running: 42 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.1%, CPU KV cache usage: 0.0%
INFO 05-17 18:22:58 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.5 tokens/s, Running: 41 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.1%, CPU KV cache usage: 0.0%
INFO:     ::1:32817 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:23:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.2 tokens/s, Running: 40 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO:     ::1:32866 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:23:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 40 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO:     ::1:32962 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:23:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.1%, CPU KV cache usage: 0.0%
INFO 05-17 18:23:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.7 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:23:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.3 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.3%, CPU KV cache usage: 0.0%
INFO 05-17 18:23:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.1 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.3%, CPU KV cache usage: 0.0%
INFO 05-17 18:23:40 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.2 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.4%, CPU KV cache usage: 0.0%
INFO 05-17 18:23:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.2 tokens/s, Running: 39 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.5%, CPU KV cache usage: 0.0%
INFO:     ::1:32800 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:23:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.1 tokens/s, Running: 38 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO 05-17 18:23:58 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 19.2 tokens/s, Running: 38 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO 05-17 18:24:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.5 tokens/s, Running: 37 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO:     ::1:32924 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:32802 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:24:09 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.2 tokens/s, Running: 36 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.5%, CPU KV cache usage: 0.0%
INFO 05-17 18:24:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.4 tokens/s, Running: 36 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO 05-17 18:24:19 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.4 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.5%, CPU KV cache usage: 0.0%
INFO:     ::1:32936 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:24:25 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO 05-17 18:24:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-17 18:24:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.1 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-17 18:24:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.5 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-17 18:24:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.9 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-17 18:24:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.0 tokens/s, Running: 35 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO:     ::1:32826 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:24:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.7 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-17 18:25:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-17 18:25:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-17 18:25:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-17 18:25:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 34 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:25:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.3 tokens/s, Running: 33 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO:     ::1:32854 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:25:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.8 tokens/s, Running: 32 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO:     ::1:32968 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:25:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.2 tokens/s, Running: 30 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO:     ::1:32950 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:32850 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:32908 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:32806 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:25:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.1 tokens/s, Running: 28 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO:     ::1:32832 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:25:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.1 tokens/s, Running: 27 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-17 18:25:56 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.8 tokens/s, Running: 27 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 18:26:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.3 tokens/s, Running: 27 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 18:26:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.4 tokens/s, Running: 26 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO:     ::1:32820 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:26:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.1 tokens/s, Running: 26 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 18:26:20 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.1 tokens/s, Running: 26 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-17 18:26:27 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.0 tokens/s, Running: 26 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-17 18:26:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.0 tokens/s, Running: 25 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO:     ::1:32932 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:26:40 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.6 tokens/s, Running: 25 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-17 18:26:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.6 tokens/s, Running: 25 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-17 18:26:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.0 tokens/s, Running: 25 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO 05-17 18:26:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.4 tokens/s, Running: 25 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO:     ::1:32790 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:27:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.4 tokens/s, Running: 24 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO 05-17 18:27:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.1 tokens/s, Running: 24 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:27:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.2 tokens/s, Running: 24 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:27:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.8 tokens/s, Running: 24 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.3%, CPU KV cache usage: 0.0%
INFO:     ::1:32884 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:27:27 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.5 tokens/s, Running: 23 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO 05-17 18:27:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.6 tokens/s, Running: 23 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO:     ::1:32876 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:27:40 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.6 tokens/s, Running: 22 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO:     ::1:32942 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:27:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.4 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-17 18:27:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.4 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-17 18:27:58 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.1%, CPU KV cache usage: 0.0%
INFO 05-17 18:28:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.4 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.2%, CPU KV cache usage: 0.0%
INFO:     ::1:32788 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:28:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.1 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO 05-17 18:28:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.0 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO:     ::1:32910 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:28:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.0 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-17 18:28:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.9 tokens/s, Running: 19 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%
INFO:     ::1:32956 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:32873 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:28:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.1 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO 05-17 18:28:38 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.9 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-17 18:28:43 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.8 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-17 18:28:48 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.8 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 18:28:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.8 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 18:28:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.8 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.9%, CPU KV cache usage: 0.0%
INFO 05-17 18:29:04 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.8 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO:     ::1:32948 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:29:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.0 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 18:29:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.9 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO:     ::1:32796 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:29:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.1 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-17 18:29:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.1 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.7%, CPU KV cache usage: 0.0%
INFO 05-17 18:29:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.2 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 18:29:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.1 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.8%, CPU KV cache usage: 0.0%
INFO 05-17 18:29:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.1 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO:     ::1:32952 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:29:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.5 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO:     ::1:32940 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:29:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.6 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.4%, CPU KV cache usage: 0.0%
INFO:     ::1:32960 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:30:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.9 tokens/s, Running: 12 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:30:08 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.2 tokens/s, Running: 12 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:30:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.2 tokens/s, Running: 12 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.3%, CPU KV cache usage: 0.0%
INFO:     ::1:32808 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:30:19 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.1 tokens/s, Running: 11 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.1%, CPU KV cache usage: 0.0%
INFO 05-17 18:30:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.2 tokens/s, Running: 11 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO:     ::1:32878 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:30:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.3 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.9%, CPU KV cache usage: 0.0%
INFO 05-17 18:30:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.7 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.0%, CPU KV cache usage: 0.0%
INFO 05-17 18:30:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.7 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.0%, CPU KV cache usage: 0.0%
INFO 05-17 18:30:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.6 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.1%, CPU KV cache usage: 0.0%
INFO 05-17 18:30:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.8 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%
INFO:     ::1:32890 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:32846 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:30:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.9 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.6%, CPU KV cache usage: 0.0%
INFO 05-17 18:31:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.6 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.6%, CPU KV cache usage: 0.0%
INFO 05-17 18:31:08 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.5 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.7%, CPU KV cache usage: 0.0%
INFO 05-17 18:31:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.6 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.7%, CPU KV cache usage: 0.0%
INFO:     ::1:32798 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:31:19 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.8 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.4%, CPU KV cache usage: 0.0%
INFO:     ::1:32966 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:31:25 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.5 tokens/s, Running: 6 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.1%, CPU KV cache usage: 0.0%
INFO:     ::1:32959 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:32931 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:31:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.6 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-17 18:31:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.0 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-17 18:31:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.1 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-17 18:31:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.1 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.6%, CPU KV cache usage: 0.0%
INFO 05-17 18:31:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.1 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.6%, CPU KV cache usage: 0.0%
INFO:     ::1:32926 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:31:56 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.9 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:32:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.2 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 18:32:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.1 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:32916 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:32:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.3 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO:     ::1:32882 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 18:32:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 18:32:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 18:32:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 18:32:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO:     ::1:32836 - "POST /v1/completions HTTP/1.1" 200 OK
Results written to .artifact/benchmarks/results/800b48f7-6104-4164-b55e-62b3760da4ee.jsonl
Killing process 87889...
/var/spool/slurmd/job3676990/slurm_script: line 45: 87844 Killed                  apptainer run --nv --home /mnt/petrelfs/huqinghao/xzyao/:/home/xiayao --bind /mnt/petrelfs/huqinghao/xzyao/code/vllm:/vllm --bind /mnt/petrelfs/huqinghao/xzyao/code/triteia:/triteia --env PYTHONPATH=/vllm:/triteia --env CUDA_LAUNCH_BLOCKING=1 --env TVM_TARGET=nvidia/nvidia-a100 --env TRANSFORMERS_OFFLINE=1 --env NUMEXPR_MAX_THREADS=128 --env USE_BITBLAS=1 --env BITBLAS_TARGET=nvidia/nvidia-a100 --env RAY_DEDUP_LOGS=0 --workdir /vllm /mnt/petrelfs/huqinghao/xzyao/images/vllm-0.4.1.sif python3 /vllm/vllm/entrypoints/openai/api_server.py --model /vllm/.idea/full_models/Llama-2-13b-hf --enable-delta --disable-log-requests --gpu-memory-utilization 0.85 --delta-modules delta-1=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1 delta-2=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2 delta-3=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3 delta-4=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4 delta-5=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5 delta-6=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6 delta-7=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7 delta-8=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8 delta-9=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-9 delta-10=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-10 delta-11=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-11 delta-12=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-12 delta-13=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-13 delta-14=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-14 delta-15=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-15 delta-16=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-16 delta-17=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-17 delta-18=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-18 delta-19=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-19 delta-20=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-20 delta-21=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-21 delta-22=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-22 delta-23=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-23 delta-24=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-24 delta-25=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-25 delta-26=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-26 delta-27=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-27 delta-28=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-28 delta-29=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-29 delta-30=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-30 delta-31=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-31 delta-32=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-32 --max-deltas 24 --max-cpu-deltas 32 --tensor-parallel-size 4 --enforce-eager
